### ISSUE TITLE
Create a MULTI OUT VST Plugin

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1]
Create multi output VST plugin. Jamtaba users can grab separated ninjam streams in your DAWs using a multi output VST plugin.
I'm thinking in a internal router. Plugin users can set a "virtual output" for each ninjam track using a combo box in bottom of track.

the idea is allow something like Kontakt, Addictive Drums, EzDrummer, etc. These plugins can be multioutput. When you insert a multi out plugin in Reaper, for example, Reaper creates many tracks (12, 16, etc), each track input binded/linked with a plugin output. With multioutput users can receive ninjam streams in separated tracks inside your preferred DAW, apply effects, recording, etc. I think is convenient and flexible to users.

**Comment by gevialex** [comment]
Hi, is this feature still a possibility? I would really love this feature a lot. This kind of feature was available in an old linux gtk app called gninjam that connected to other linux audio apps via the jack audio connection kit. http://www.gehrignet.de/cms.shtml?programming/ninjam.shtml. The author is called Gherig but it looks like the app project is pretty rip since quite a long time. I tried to build that app a couple years ago from the source with a then current linux distro and failed apparently because it required older versions of system libraries and I'm only a user, no programming skills :P

**Comment by gevialex** [comment]
Lol, I just managed to launch and old live boot linux distro with gninjam in it, just to show how you could select the output to which the audio of remote users went from a list
![image](https://cloud.githubusercontent.com/assets/16207152/17453718/e5774c26-5b56-11e6-93da-4e97663ba986.png)

**Comment by elieserdejesus** [comment]
Hi @gevialex , to implement this feature is necessary change some complicated details in the JAmtaba audio processing code. This feature is possible but is a bit complex and can be very time comsuming. Maybe in the next release ...

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
