### ISSUE TITLE
[Public chat] Jamtaba is crashing when turning on public chat and it is unable to connect

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1015]
![image](https://user-images.githubusercontent.com/15310433/36698041-911281a4-1b27-11e8-9e90-6f8d7203f339.png)

Jamtaba freezes completely in this case. Fortunately if public chat is not turned on, all works good.

**Comment by elieserdejesus** [comment]
@jonjamcam , this bug is trick, it's a issue in Qt websocket module.

To avoid recompile a newer Qt I tried just recompile a newer websocket module **and works**. I shutdown the public chat server to test and it's working, no more chashes even if the chat server is stopped.

So, at moment my Qt kit version is **5.5.1**, but the websockets module version is **5.6.3**: http://download.qt.io/archive/qt/5.6/5.6.3/submodules/qtwebsockets-opensource-src-5.6.3.zip

I'm not shure if the 5.6.3 complete Kit is compiling without errors.

**Comment by jonjamcam** [comment]
> So, at moment my Qt kit version is 5.5.1, but the websockets module version is 5.6.3: 

I recompiled my qt using the new 5.6.3 websocket module too and it's working OK now @elieserdejesus .

**Comment by elieserdejesus** [comment]
nice @jonjamcam , I will upgrade my Qt too after this release.
