### ISSUE TITLE
Allow disabling video (for slow connections or general purpose)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1021]
Last night I had a pretty good jam session with some old buddies. ATM I'm using a 3G cellphone connection which works OK using low quality encoding in Jamtaba, but connection problems start for me when video stream is enabled. 

 Video is working flawlessly in Jamtaba, no problems with that. The thing is there's no way to control the high use of bandwidth video demands except disabling each user individually.

So to be consistent, if you are using LOW QUALITY for encoding because of poor connection, I think an additional option there to disable video streams (in or/and out) could be a simple solution:

![image](https://user-images.githubusercontent.com/15310433/36935464-cdcf92aa-1ed6-11e8-9332-0b0f946f5ea7.png)

Another approach could be to have a button to do this manually at any quality:

![image](https://user-images.githubusercontent.com/15310433/36935499-50f8fd24-1ed7-11e8-89c5-cebd47bef09b.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , unfortunally at moment is not possible disable incomming video streams without disable the  audio stream too. This is the price we are paying to exploit the ninjam protocol 😄  , Let me explain in bad english:

In ninjam protocol every interval is *tagged* with an [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier). The interval is uploaded in blocks/chunks of samples, and every block of a specific interval is *tagged* with the same **UUID**. So, the receiver can join/merge all received sample blocks tagged with the same UUID and the result is a ogg vorbis stream, ready to be decoded and played. When a new interval starts a new UUID is generated for this particular interval, and the process is repeated (all uploaded chunks of the next interval will be tagged with the new UUID). For every channel xmited and every interval a new UUID is generated.

Another info is sended to ninjam server when we are xmiting: **the local channel index**. If you are using 2 local channels the indexes will be **0 and 1**, for first and second channels respectively.

It's not possible (for my knowledge of ninjam protocol) send data to ninjam server without specify a **channel index**. So, **when we are xmiting video a channel index is setted behind the scenes**.  

When I started the video feature experimentations I used the **video channel index** as **1**. This means **the second channel**. The problem I realize was: **what happens if the user is using just one channel?** What are the options? Create a *ghost* second channel, not visible in the GUI? This is possible, but I abandoned this idea and choose some more simple: **the video channel index is always 0** (the first channel), because the first channel is always created (in JamTaba).

So, when we are using **one local channel** to xmit **audio + video** we are uploading 2 streams (audio and video). **Both streams are sended with the channel index 0**.  The streams are separated in the clients (and the audio bytes are not mixed with video bytes) because each stream is tagged with a different UUID. **The UUID is the trick!!** I'm using this trick to send the audio and video in the same channel index, but keeping the uploaded bytes logically separated and identified by different UUIDs.

All good, we have cool video feature, etc. But there's a price 😄 : 

If you turn off a remote **first channel** (turn off xmit) you are turning of all data incomming in **channel index 0**. You are disabling audio and video, because video is received in the first channel too.

**Summarizing:** in the current scheme is not possible disable incomming video without disable the audio for the first channel. 

About the current scheme:
- Use the second channel to xmit/receive video is problematic like use the first channel.
- Create a third channel named "video" is the best option (it's clean and allow disable video without affect audio channels), but public servers **max channels** is 2. Is not possible create the 3rd channel.
- Change the ninjam protocol to accept video (we are in 2018 😄) is the clean way, but is very complicated in a community level (all servers must use the "ninjam 2" servers implementing the new protocol). 

In the end I considered the options and choose the more simple, but with side effects.

Another Ideas are very welcome!

**Comment by jonjamcam** [comment]
Ohh I see it's a complex matter. Thank you for the detailed explanation @elieserdejesus . 

Another idea to address rhe problem I don't know if it's technically possible: lower the video fps when using low quality encoding as an option. I think a slideshow of images instead of smooth video could be good tradeoff.

**Comment by elieserdejesus** [comment]
> lower the video fps when using low quality encoding as an option. I think a slideshow of images instead of smooth video could be good tradeoff.

This is possible, the code is prepared for this change. But is not possible change the fps in the "others" machines. We can reduce our fps, but we still receiving high fps from others. At moment JamTaba is using 10 fps.

**Comment by jonjamcam** [comment]
> We can reduce our fps, but we still receiving high fps from others.

So does this mean that reducing local fps will not reduce the downstream bandwidth usage?

**Comment by elieserdejesus** [comment]
> So does this mean that reducing local fps will not reduce the downstream bandwidth usage?

Exactly @jonjamcam . Reducing your fps will reduce only the upstream bandwith usage. The only way to reduce downstream usage is ask others to reduce fps. 

It's similar to **sample rate** in audio. If some ninjamer is streaming at 96 KHz you will see high usage in your downstream bandwith.

**Comment by jonjamcam** [comment]
I see no good solution for now, except for me to get a better connection 😀. @elieserdejesus you have put a lot of effort to make the impossible work and I think jamtaba is working very smoothly atm, so why break it? I remember the problem we had with utf-8, endless discussions. And finally the best solution was so simple. But it had to be done on the other side (cockos). So I agree with you that the best solutions need modification on the server side. Let's hope in the future video is used more and more so improvements are needed by the whole community on the server side (3rd channel or modernize the ninjam protocol).

For me the solution is simple. Get a connection that would let me enjoy jamming as it should be. I think 4g can handle very good video bandwidth requirements. Maybe try fiber at home. I'll see. Closing for now

**Comment by jonjamcam** [comment]
Just to share my experience of the las two days. If no video is present a 3G cellular connection can handle full server jams with no problems. For videojamming you need 4G

**Comment by elieserdejesus** [comment]
> For videojamming you need 4G

At moment video stream is 3x bigger than audio, even using small resolution and low fps. The codec used at moment is not the best in size (mpeg4). The **h.264** codec is very good in image quality and generate smaller video files (less data to upload/download).  

JamTaba is using ffmpeg, and ffmpeg can use h264 or another codecs. It's necessary recompile ffmpeg including the codec libs, and possibly some small adjustments in the code. I created an issue: https://github.com/elieserdejesus/JamTaba/issues/1043

**Comment by jonjamcam** [comment]
no  more problems for me. got 4G now:

![image](https://user-images.githubusercontent.com/15310433/37518991-57b8ea06-28f6-11e8-940f-2129320e2ffe.png)

 :smile:

**Comment by jonjamcam** [comment]
video working smooth @elieserdejesus in 4G. Just wanted to share some snaps:

![image](https://user-images.githubusercontent.com/15310433/37949283-55aae9cc-316a-11e8-9be4-4b21bad2e7b7.png)

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , very nice pic. Just curious: What notMe was xmiting? It's a robot animation?

**Comment by jonjamcam** [comment]
> What notMe was xmiting?

It looked like his camera pointed to an unusual location jajaia
