### ISSUE TITLE
Use h.264 as video codec

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1043]
Test h.264 as video codec to see if is possible reduce the video stream bandwith usage.

ps: use mp4 as container.

**Comment by jonjamcam** [comment]
Hopefully h.264 can improve image quality too. For example the grid layout shows big squares when fast movements are used. 

![image](https://user-images.githubusercontent.com/15310433/37630695-c7d7a590-2bc4-11e8-98e7-b9927e37ea32.png)

the old dilema bandwidth v/s quality. :unicorn:

**Comment by elieserdejesus** [comment]
> the grid layout shows big squares when fast movements are used.

In this case the guilty is not the video codec 😄 . JamTaba is setting the cam to the minimum available resolution. So, we are receiving very small videos (in resolution), but grid layout is resizing/stretching these small videos, so we see these big squares.

I guess the squares will be visible with another video codec too, maybe a little smoother.

**Comment by jonjamcam** [comment]
Question: from what I read here:

https://www.google.cl/amp/tubularinsights.com/encoding-formats-mpeg4-vs-h264/amp/

I have the feeling that h.264 will use more CPU resources than mpeg4. 

So my question is will the "old" jamtaba be compatible? or we'll all have to migrate to the new version?

I ask this because I still use my old laptop which only 2 CPU and ATM video is working fine for me (although the quality is low and the bandwidth usage is high)
