### ISSUE TITLE
Jamtaba for the iPhone/ iPAD

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#105]
Guys I remember some time ago, Torben asked this question that I think could be relevant...From the ninbot forum........

********
A Ninjam App would be awesome

Submitted by Torben Scharling on Thu, 01/24/2013 - 15:41. 

Howdy ppl, I was just thinking - how hard would it be to make a ninjam client app for the iPhone/iPad ?

Now that my computer is at the repair shop, again, and I'm stuck here with me ol pc laptop, yet having a shiny iPhone 5 in my hands, I can't help but think how awesome it would be, to be able to connect to Ninjam and Ninbot servers directly through my iPhone! 

I'm digging the http://ninbot.com/iplay player btw, works awesome! Would be cool if the capability, to skip to the next or previous track worked with the iPhone's player controls, as the play and pause, and background playing works nicely already.

So thanks Tom, and whoever else are/would be working on these things :)

************

so, Jamtaba for the iphone/ipad?

**Comment by elieserdejesus** [comment]
Is possible: [http://doc.qt.io/qt-5/ios-support.html](http://doc.qt.io/qt-5/ios-support.html)

But to have Jamtaba in the apple store we need pay. I think is about U$ 100 per year.

**Comment by jonjamcam** [comment]
well......this will be the shortest thread I think...lol

**Comment by Ezeer** [comment]
Perhaps not jon .
What license are we using ?
Imagine the guy full of money , with the idea to earn more with our work using iphone bizness ?
Aaaaaarrrrgh .
So perhaps we should protect our rights by now ?

**Comment by jonjamcam** [comment]
this will always be a question with open source software.......It's an ethical issue.......I see it like this:

If someone invest his own money to expand the software to a different market and the program is used by more people, then this person gave something back to the comunity....more exposition....maybe to a market where you'd never dream of going into......and he/she made some money........

**Comment by Ezeer** [comment]
mmm... u like that guy ?
The community loves that guy ?
Hey , but i can be that guy too .
I just make a fork , a port , and i'm done .
You want some love ? Give the money first !
You got no money or ipad ? Die sucker !

Thanks for the idea Jon !
:+1: 

lol...

**Comment by elieserdejesus** [comment]
At moment we don't have a licence. It's in github, so everybody can use, it's public.
I'm not shure if we have a GPL or LGPL work here. 
I prefer GPL, but I'm no shure if we can use GPL using Qt. I'm not good with licences, so, if you guys have some light in this field please share.

Jon, about your question: All open source software can suffer from somebody getting the code and make money. The problem is somebody get the code, build a closed source version, and make money. If you have another version, make money, but your version is open source too you are ok, this is not a problem for open source licences (I'm not 100% shure this applyes for all licences).

If somebody use our work in a closed source nobody in this world can learn reading the code, inspecting the solutions. 
I will write here the same thing I write in a email sended to Ezee: If the guys from Wahjam, ninjam, vsthost, vstboard, etc. don't share your knowledge I never will be able to write the Jamtaba code. I learn a lot inspecting the code of these guys. When I decide open the Jamtaba source my motivation was: I will share the code to inspire others, because other more experienced programmer do exactly the same for me. It's a retribution. I receive a lot of knowledge from other programmers, so I'm sharing this too. 

Off course I don't expect every body in this world will "match" with this philosophy. So we really need some licence. But even using a licence, every programmer can COPY a block of Jamtaba code, paste in your code, compile, make money, etc. No licence in the world can stop this.

**Comment by jonjamcam** [comment]
"I just make a fork , a port , and i'm done ."

You could do it, play the $100 a year, earn a lot of money and create a fund for future development of jamtaba, for example. But that's an individual decision.

 I'm not into this project for money....I share Elieser, philosophy explained above.

**Comment by elieserdejesus** [comment]
Let me share with you what I say for my wife every time she ask me:  "but what if others get your code and publish the software to make money?"
- If the software is just published in other place, without any improvements, why people will pay for this version if we have the same software for free?

But my wife never stop, and she ask again: "but what if someone improve Jamtaba and tries to make money from your work?"
- If somebody get this code, improve, make a kicking ass tool to play online called MoneyTaba, I will stop my work with Jamtaba and will use MoneyTaba, because if MoneyTaba is really good, as a musician I want this kicking ass tool to play online.


Jamtaba is not about money, but I'm not excluding the possibility. For example: who pay the server costs? At moment nobody, because I'm using GAE (Google App Engine) and the server traffic is not huge enough to generate some cost. But GAE has my credit card number :) When the traffic is enough to generate costs...

Keep a open source project in github is one thing, keep a "online music jam session service" is another thing. 
Another "money" example is Tom, from ninbot. Tom is making money using the ninjam server original code. But Tom write improvements in this code, and he is keeping the servers for years. So he is supporting a "jam service" for all ninjamers, and he create a place to the community (ninbot.com). So, in my opinion this guy deserve every cents.  
But we have some problems: if I have a Jamtaba ninjam server, and I'm interested in the fancy features of ninbot servers, like the lounge chat, where is the code? The code is not opened, I suppose.  
So welcome to the licence war world, a weird place! :)

**Comment by Ezeer** [comment]
Bill gates made money like this , everybody love bill gates !
In france we got dreads that sing : " If u got no money u got no friends " 
Reload ! ( i have a license to kill ! )
https://www.youtube.com/watch?v=ja9-MJRPyRs

**Comment by jonjamcam** [comment]
https://www.youtube.com/watch?v=ZnSbrx5YByY

**Comment by elieserdejesus** [comment]
Hehe, another day my sister say something I disagree, but is very funny:
"I agree that money does not bring happiness, but I prefer to be sad in Paris"

And I have another, and this one is about logic:
"Money does not bring happiness, but it can buy a jet ski, and I've never seen anyone sad in a jetsky"

He he he! Funny logic!

About the licence: I suggest the licence WWBYH (We Will Burn Your House). If you use our work to make money and don't share this money we will find you and burn your house. But first we will save the money, and after we will burn the house. :)

**Comment by jonjamcam** [comment]
"WWBYH"

I love it!

**Comment by Ezeer** [comment]
AH AH AH ! I love you guys !
LOL !

**Comment by elieserdejesus** [comment]
Jon, you know jammr is based in wahjam. Jammr is the closed version of wahjam. Jamtaba exists because the jammr/wahjam guy (Stefanha) share your knowledge here [Ninjam Protocol](https://github.com/wahjam/wahjam/wiki/Ninjam-Protocol).

**Comment by jonjamcam** [comment]
Yes.That's my point exactly. Stefanha has his own site with private servers and premium features, but he has contributed very much as you say to the community. I was trying to argue that there's no problem if someone wants to use open source code to create a business. The problem comes in my opinion when there's no giving back in return.....

BTW i played once with stefanha and he seemed to be a nice guy.
