### ISSUE TITLE
Video in grid layout sometimes get cropped depending on theme, number of players, etc.

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1067]
![image](https://user-images.githubusercontent.com/15310433/37944293-60b19c44-3151-11e8-812b-ba019a073539.png)

![image](https://user-images.githubusercontent.com/15310433/37944330-770ae5b8-3151-11e8-8720-098d63ea1851.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm scared 😄 :
![image](https://user-images.githubusercontent.com/1012741/37963974-5514ce34-3196-11e8-8934-6bdd4521a967.png)

**Comment by jonjamcam** [comment]
Trashcan's video consumes a lot, but probably that was a peak or a wrong Reading. Not the average for his video.

**Comment by jonjamcam** [comment]
@elieserdejesus It looks that the grid view adjusts itself automatically in width and height. Maybe if the user had a little more control over that as it is now with the font size in chat it would be great, because the layout is very different if there are 2 or five users, or the theme is game.

**Comment by elieserdejesus** [comment]
> you can't get this 3X2 grid always specially in small screens and laptops, so in this case I had to collapse the chat

> another thing that it's important. Video users not always appear at the top, so sometimes when your layout is too big and you have to scroll, some cams get outside the remote channel view. In an ideal world, videocams should be at the beginning

@jonjamcam, I agree 100%, but I'm avoiding change grid layout because my idea is **drop the grid layout** from JamTaba. 

The grid layout was created to allow bigger cams, but **is not good enough**. Andy suggested a **separated "cams only" window**, I like the idea and I think this is **the best solution to show nice cams**.

***
The idea is:

1. keep **only the horizontal and vertical** layouts (drop grid layout)
2. The vertical and horizontal layouts will **keep showing the small cam previews**, no changes.
3. Clicking in a **small and special button** in the small cam preview widget **a new window (like the floating metronome or looper window) will be opened and the cam (bigger than the preview) will appear**.
4. If you click in other cams preview widgets the cams will be added in the "cams window" too. The general idea is: you can add or remove the cams from the "cams window".
5. The "cams window" can be **camera images only**, or maybe **cams + level slider only**, etc. 

I think this idea is better than grid layout because grid layout always will have problems in small screens.

**Comment by jonjamcam** [comment]
> Clicking in a small and special button in the small cam preview widget a new window

Good solution for the long run. Cams should be in a separate window for the best experience. I agree.

> keep only the horizontal and vertical layouts (drop grid layout)

I disagree on this one. The grid layout works very well in small screens and when you have only one. The ability of having everything in one window is very useful too most of the times. Since implemented I only use this layout, so please don't drop it .
