### ISSUE TITLE
the mouse  pointer is not big enough and hard to see

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1083]
A long time that i have this issue not particulary with the last version but must be around version jamtaba2 i think.
the pointer  in jamtaba is not an arrow but just a  vertical thin bar  and hard to see where it is on the screen.

jamtaba 2.1.4 as vst in reaper

**Comment by elieserdejesus** [comment]
@DoublebassOO , I tested here and the mouse pointer is always an arrow, **except when you click in a text field** (like the channel name, user name or chat text field). 

When you click in a text field the pointer changes to a vertical line, exactly as you described.

I think you are seeing a vertical line as pointer because some text field is focused. The vertical line pointer is the expected behavior.

**Comment by DoublebassOO** [comment]
no really a vertical bar. No arrow, and after clicking black a arrow often.
