### ISSUE TITLE
Standalong is using wrong icons

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#110]
Standalone is using the old gray icons.

![image](https://cloud.githubusercontent.com/assets/1012741/11040747/04f0b8bc-86f5-11e5-9699-c01d1cb78b66.png)

**Comment by jonjamcam** [comment]
on win10 the taskbar icon is the new one

![working on win10](https://cloud.githubusercontent.com/assets/15310433/11042976/103dbc2a-86f9-11e5-9d17-803aa744bfaf.jpg)

**Comment by elieserdejesus** [comment]
Humm, I will test in my virtual machines, I think my windows is doing some black magic caching in icons.

**Comment by jonjamcam** [comment]
When this happens to me I restart thecomputer....lol. BTW win7x64 is behaving as you describe...ALL BLACK

**Comment by Ezeer** [comment]
Same old icons in Jamtaba window and task bar but ... MIDI IS WORKING NOW FOR ME  !!
Nice promotion ... for the poor midi devices , eh eh !

@elieserdejesus  I suggest you not only give the number but also the RC3 in the main window's caption. Or in the About option menu ....

Because testers need to rely on precise information , **communication is our POWA** !
![bigstock-leadership-power-concept-d-i-44991157](https://cloud.githubusercontent.com/assets/1283808/11048479/72a4b15e-8738-11e5-80a7-bdba1a479d18.jpg)
