### ISSUE TITLE
Mute button in local "your control" channel muted output to the jam

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#112]
This is different behaviour than ninjam or reaninjam. In the manual I expected to work the traditional way, but I think this is less confusing for new users.

Should I correct the manual? or is it a non expected behaviour?

**Comment by elieserdejesus** [comment]
Jon, I think we need keep this behavior (when mutted the channel is not sended). 
I can think in one situation when this behavior is a problem: direct monitoring. If a Jamtaba user is using direct monitoring in your sound card probabily the user want mute the input channel, and this will not work as expected because the audio is not transmited. But direct monitoring in ninjam is a very bad thing, so my opinion is keep this xmit + mute behavior.

**Comment by jonjamcam** [comment]
I agree completely. For me it was very puzzeling at first, but one get used to it with time passing.  So I will change the manual...
