### ISSUE TITLE
Jamtaba remembers most plugins settings when restarted, but others' settings are not stored

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#113]
I like a lot the REAGATE plugin . The Cockos guys released a separate plugin pack for any DAW with the reaplugs, but reagate, reacomp will not remember previous session setting, but readelay WILL!.

I tested reaper with this seaprate reagate and after shut down it remembers ok, so It's a Jamtaba issue.

http://reaper.fm/reaplugs/

**Comment by Ezeer** [comment]
I noticed also that solo mute is not saved on the main tracks .
( while Mute was ... )
Can you tell me if it's also your case please ?

**Comment by jonjamcam** [comment]
True, Ezee. But the function of the SOLO in the traditional way (i.e. recording studios, sound reinforcement, etc.) is always temporary. Mixer consoles use it to check if one channel is sounding right in a general sense. It is not meant to be used as permanent.

**Comment by Ezeer** [comment]
I am planning to use the configurator class i am working on to save sessions setups .
( yeah , save your actual settings in a separate folder wich will contain a Json file . Or perhaps
a single Sessions folder , with Json files inside )
So you could save snapshots of setups , to do a semi-automation ( things are not mooving by time but
when you load the snapshot . )
Today , you are allowed to have " only " 3 tracks , but tomorrow , who knows ?
^^

**Comment by elieserdejesus** [comment]
The bug in "remember" some VST plugins state is related to the way plugins externalize your data to save. Some plugins externalize your state in a binary block of data, so store is just put this data in a file, and restore this when Jamtaba is opened. But I think some plugins don't work in this way, and we need ask "how program number is selected at moment?", and save this info. This can be trick because some plugins are complex. I don't know how diffentiate these "store schemes" in VST plugins. In my tests I see Jamataba can't remember the state of old plugins, but the new/modern plugins can externalize your internal status in a binary data and works great.

@jonjamcam , we need at least the name of the bad plugin, so we can check the VST version or another detail with we can use as a clue to solve the problem.

Ezee, I think save the solo button state is not necessary, this can be confuse to non advanced users. If some user press solo by mistake and close Jamtaba, in the next session solo is pressed and maybe the users will not hear anything usefull, and don't realize the solo is pressed. Some begginers don't know what is the SOLO button, so I think is better avoid these little problems. Save the mute status make sense, specially for metronome.

**Comment by jonjamcam** [comment]
Obsolete... closing
