### ISSUE TITLE
multiprocessor handling?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#114]
hi Guys.

How does the Standalone handles mutliprocessor computers? I mean, as VST instruments consume a lot of resources they should be handled separately from the server/ASIO functionality, Seems to me the logical thing to do for two or more processsors. Does it make sense?

I have the experience with Kontakt in my laptop. Some kontakt instruments are really cpu hungry (like NI abbey road modern drums) and as a drummer it's not comfortable to play at higher buffer sizes. So when used intensively It sometimes makes the ASIO4ALL crumble,interrupting the flow of the jam. When this happens I have to stop playing.

As you know Kontakt has multi cpu support by itself and I don't know is it's a good idea to use that feature with Jamtaba or not (I have it turned on right now and the ASIO problem happens sometimes, so I'll turn it off in the next jam to test). We should address BTW this issue in the manual so users can configurate correctly this kind of plugins, don't you think?

BTW I can't say enough that Jamtaba is currently the BEST SOUNDING NINJAM CLIENT OUT THERE. Additionally it's the most flexible and easy to use. It's really and xperience.

ThX guy for all your hard work. It's really happening..for me!

**Comment by elieserdejesus** [comment]
Jon, at moment Jamtaba is using your processor cores to run different things. Audio, GUI, audio encoding are running in different "threads". You can think in a thread as a "Virtual processor".

I think we can't separate the audio from VST processing, not in a realtime audio environment. This is possible in a DAW using offline processing. The VSTs need be processed in the audio "thread". But we can change the code to improve the performance in multi core processors if the tracks (local or remote) are processed in parallel. At moment the tracks are processed in a serial way. First Jamtaba process the local input 1, after local input 2, after the ninjam track 1, ninjam track 2, ninjam track 3, etc.

This can be very improved processing in parallel. If you have 4 processor cores Jamtaba can process 4 tracks in parallel, because there is no dependency between tracks, each track is isolated from others.

This kind of optimization can be trick and generate subtle bugs, so it's a big thing, we need work in something like this with a lot of calm, and a lot of coffee :)

**Comment by jonjamcam** [comment]
OK now I understad that more musicians in a room require more resources!

I made an experiment some days ago with win xp. The results can be of some use :

Just changing from the room tab to the main page tab during a jam, the performance improved substantially:

![xp test_room vs main](https://cloud.githubusercontent.com/assets/15310433/11061994/e1df1a22-8789-11e5-8b3e-c4d2ed515ed0.jpg)

**Comment by elieserdejesus** [comment]
Jon, two things:
1 - The pan dial is very ugle. This is not the normal pan dial. It's a Win xp issue?
2 - When you enter in a room a lot or audio processing is running behind the scenes. We need decode the ninjam streams (these streams are ogg vorbis encoded), resample (because ninjamer use different sample rates), mix all the streams (including metronome and your inputs) and finally generate some audio output.
3 - Audio decoding is not a big issue. The big problem is audio encoding. When you create 2 local channels you are using 2 ogg vorbis encoders. This will use a lot of processor power. Try remove one local channel and you see the difference. This is something we can improve in the future too, but this optimizations are always complicated.

**Comment by jonjamcam** [comment]
1.- Yes. Only in Xp the pan loos like this.

3.- I noticed that, Elieser. I use only one channel when playing, but when I test I like to see the limits......

This kind of behaviour I discovered motivated https://github.com/elieserdejesus/JamTaba/issues/50 . I just try to understand because the only difference is in changing tabs. I changed nothing else. There's the same members in the room, same channels, etc.

**Comment by jonjamcam** [comment]
about kontakt I must say it works much better WITHOUT the multi cpu. I turned it off and it just flies

**Comment by elieserdejesus** [comment]
Good news! 
A possible explanation: Jamtaba is using your cores to run audio, GUi, and encoding. So you don't have many other free cores available to Kontakt, is better disable the multi cpu.

**Comment by jonjamcam** [comment]
Yes. Just had a 1 hour jam with full room and no problems with kontakt. I was monitoring my cpu during the whole jam and looked very stable. If i had a 3rd hand or foot I would have taken a snapshot :D

**Comment by Ezeer** [comment]
**If i had a 3rd hand or foot I would have taken a snapshot **
ah ah ah ....

**Comment by jonjamcam** [comment]
![jam mini kontakt](https://cloud.githubusercontent.com/assets/15310433/11076322/d362eb96-87d8-11e5-804b-39c297329b8a.jpg)

rented a third hand really cheap!

**Comment by Ezeer** [comment]
" rented a third hand really cheap! "
Yo! You could have used also an extensible part of your body that is free .
( mwah aha )

4% of cpu use ...woaw !
I have found in the PortAudio sources some helper functions to deal with cpu use per callback : 
 >@brief Functions to assist in measuring the CPU utilization of a callback
 stream. Used to implement the Pa_GetStreamCpuLoad() function.

> @todo Dynamically calculate the coefficients used to smooth the CPU Load
 Measurements over time to provide a uniform characterisation of CPU Load
 independent of rate at which PaUtil_BeginCpuLoadMeasurement /
 PaUtil_EndCpuLoadMeasurement are called. see http://www.portaudio.com/trac/ticket/113
*/
https://subversion.assembla.com/svn/portaudio/portaudio/trunk/src/common/pa_cpuload.c

**Comment by elieserdejesus** [comment]
Ezee, I'm working in a performance monitor branch here. At moment is working, I'm showing the cpu and memory usage. I'm relying in windows API to measure CPU and memmory usage, but the values are just close to the values showed in task manager.  
If you are interested I can push this branch and you can tweak somethings.

![image](https://cloud.githubusercontent.com/assets/1012741/11088592/ac1de67c-884a-11e5-8cd7-5615f6c5c6ca.png)

**Comment by Ezeer** [comment]
Yes , i can give it a try with the PortAudio helper funk .
Thx elieser

**Comment by Ezeer** [comment]
Your link is dead .
Below a view of PortAudio approach : 
![cpuload](https://cloud.githubusercontent.com/assets/1283808/11089267/c4893d9c-8868-11e5-885f-67224a1c60c1.png)

**Comment by elieserdejesus** [comment]
Ezee, I suppose portaudio will return only the audio thread cpu usage, right? Portaudio audio don't know about other threads. In Jamtaba the audio encoding stuff is running in a separated thread, so we need count this cpu usage too. And we have a lot of cpu usage in the Qt thread, running GUI, network, etc.

**Comment by Ezeer** [comment]
Yeah , i think PortAudio approach could serve to mesure the Tracks/VST loads , not Jamtaba App loads  .
That could fit with #93 request about plugins .
