### ISSUE TITLE
Webcam problem.

### ISSUE THREAD

**Issue by Brouilles** [elieserdejesus/JamTaba#1177]
Hi, 
I just compile the program for Windows and Mac OS. But the camera don't work. On Windows, the icon is not visible. And on Mac OS, I have the icon, I can click on it, the camera turn green and stop (I have added in the plist the lines for Camera and Micro access). 
The application show me the Mac OS microphone authorisation, but not for Camera.

OS: Mac OS Mojave
Windows: Windows 10 (compilator: MSVC 2013 express edition)
QT: 5.5.1

But, when I install the original version of the program, this working. So maybe a problem with dependency?

Any idea?
Thanks.

**Comment by elieserdejesus** [comment]
Hi! 
Is Your Qt static compiled? 

If yes, the module QtMultimedia is available in your Qt libs folder?

**Comment by Brouilles** [comment]
Hello,
I use the QT binaires include un the installer. And I have QTMultimedia. Strange, it’s working on the machine compile the program, but don’t work on others (Windows / Mac OS). For Mac OS, I use macdeployqt for add dependencies in .app. I have the Webcam icon, the webcam light turn green and return back. With no error. But, if I open the binary of the program inside the .app, the camera work correctly.

And no error on Windows, just webcam Icon  not showing.

So it’s very strange. I don’t understand...

**Comment by elieserdejesus** [comment]
> But, if I open the binary of the program inside the .app, the camera work correctly

So you have no problem with compilation or dependencies, because it's working fine when  you run the binary directly.  I'm not a Mac expert user, but I'm suspecting of some privilege problem in your .app. This is the only thing I can imagine at moment.  

> And no error on Windows, just webcam Icon not showing.

Sorry, I have no ideas here too. If you have all Qt libs I can imagine why your webcam is not working. I suggest create a very simple webcam application in Qt and try to isolate the problem. I can't remember but I think Qt has some camera examples. If yes, just try to compile this example. If the example not work you have a more general problem, if work it's something in JamTaba side.
