### ISSUE TITLE
Compile/install on Linux

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1200]
Hi @elieserdejesus. I've been unable to find instructions on how to compile a linux 32bit/64 bit version as static. I'm in the process to migrate to linux mint and I need both 32 & 64 bit standalone versions. Any clues on where to begin?

As a commentary I tried to install Jamtaba on ubuntu x64 with no success. The learning curve for linux is steep.

Thanks in advance

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I`m compiling and testing in a Ubuntu 64 bits, version 18.
I`m using a virtual machine, just to be 100% clear.

I need fix some compile scripts for linux, but I don`t know if will work in linux mint too.

**Comment by jonjamcam** [comment]
> Im using a virtual machine, just to be 100% clear.

I'm testing various linux distros booting from a pendrive. No install atm.

If I download Reaper for linux it works on both Ubuntu and Mint right away, but Jamtaba is not. I believe there should ve not much difference. 

 Easy install is the beginning of easy of use. Of course I'm a new linux user, so it's probably something I didn't do right, but It's worth point it out.

**Comment by elieserdejesus** [comment]
In Linux I'm not using Qt static compiled. 

- Install Qt using *apt get*
- Instal QtCreator
- Open the Standalone Project (Standalone.pro) and compile

**Comment by jonjamcam** [comment]
Thx @elieserdejesus . I'll try that!

**Comment by arnaudlecam** [comment]
Hi @jonjamcam ,
I agree with you : "Easy install is the beginning of easy of use". And I think packaging could do the work.
That's why I'm trying to package JamTaba.
As I said in a [pull request](https://github.com/elieserdejesus/JamTaba/pull/1261#issue-402435795), compiling on linux was a bit tricky for me.
At starting point, I had to link precompiled libs with mine (with `ln -s`), to avoid `Undefined reference` problems (`__powf_finite`, `__log2_finite`, etc.): I think precompiled libs were compiled with GCC<2.31 ([see here](https://github.com/google/filament/issues/2146#issuecomment-590101241)), but a lot of linux distros work with GCC>2.31 now.
Linking with my libs worked, except for minimp3 & miniupnp (I use my dirstro packages, except minimp3 and a few miniupnp libs witch are not actually packaged).
I hope it will help you...

Then I had to find VST2: a bit tricky to...

As suggested by @elieserdejesus , I'm trying to make tests now. So I need qtcompiling under linux, targeting Windows & Mac OS: I'm trying with [Martchus PKBUILDS](https://github.com/Martchus/PKGBUILDs.git), without any succes at this time: I'm not able to create Windows & Mac OS devices under QT Creator, and I don't know how to compile out of Qt Creator.

**Comment by elieserdejesus** [comment]
@arnaudlecam . I don`t think cross compiling will solve the problem. Here I`m using windows as main OS and compiling with visual studio 2013. To compile Linux and Mac I`m using virtual machines. Using VirtualBox to run an Ubuntu 18 and VMWare to run a Mac image. 

As you can see I`m not trusting cross compiling. I think cross compiling will work for libs, but not shure if it the right tool to compile JamTaba.

**Comment by arnaudlecam** [comment]
ok @elieserdejesus , I'll take that way thank you.
Witch one for Mac, please ?

**Comment by elieserdejesus** [comment]
> Witch one for Mac, please ?

https://www.wikigain.com/install-macos-sierra-10-12-vmware/

**Comment by arnaudlecam** [comment]
Hi @elieserdejesus ,
Compiling and running under Sierra 10.12 finally worked (with Virtualbox), but a `LIBS+= -lz` line had to be added, juster after `LIBS += -framework Cocoa` in Standalone.pro
Am I missing something, or should it be commited ?

**Comment by elieserdejesus** [comment]
> Am I missing something, or should it be commited ?

Please commit, and thanks for your time testing 👍
