### ISSUE TITLE
Your Jamtaba version is not compatible with previous versions!

### ISSUE THREAD

**Issue by duxsmer** [elieserdejesus/JamTaba#1221]
Jamtaba is awesome, but only ran once. Now I get this error. Please help!

**Comment by Oakridge99** [comment]
me too
worked last night on 
now same message

**Comment by duxsmer** [comment]
Should have mentioned I an running OSX 10.13.6. Tried reboot and PRAM reset to no avail. Even tried installing older version.

**Comment by duxsmer** [comment]
Also worth noting that 2 applications appear like they are trying to open simultaneously when I attempt to launch the application.

**Comment by mixticninja** [comment]
Same issue, tried to downgrade but "doesn't mean anything message :  **version is not compatible with previous versions**", still there before crash on app and vst, with  windows 10 64 bits version

**Comment by zeppelinux** [comment]
For me it failed with the same message after totally fresh install. 
Mac mini.

**Comment by Krill0** [comment]
Same for me, win 7 64-bit, fresh install.

**Comment by Oakridge99** [comment]
would you believe--its working again!

**Comment by elieserdejesus** [comment]
Hi guys, the error is related with the server dayly quota being exausted again (the problem is severe in weekends). I will drop the server, it`s costing some money (check the image) and generating many problems. I`m changing JamTaba code to query data from ninbot (the admin Tom is helping a lot), so the jamtaba server will not be necessary in the next days (I will release a new JamTaba version ASAP).
![image](https://user-images.githubusercontent.com/1012741/77843799-edec7e00-7176-11ea-85f7-359550ef0748.png)
