### ISSUE TITLE
Allow conventional standalone audio drivers

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1222]
On Windows Jamtaba standalone only works with ASIO drivers. Is it possible to be able to use Wasapi, mme, etc. just as most audio software do?

**Comment by elieserdejesus** [comment]
@jonjamcam , the problem is receive a lot of complaints about audio latency due to bad buffer size configuration, etc. 

Wasapi is a very good API, but I see some computers (from my students) where the performance of Wasapi was terrible. Sometimes just don`t work. For while It`s not reliable like ASIO.

MME is not a possibility for this application, the latency is very high.

Common (non geek) users will blame JamTaba for every audio driver latency problem. We will just spend time explaining about "buffer sizes", etc.

From time to time I`m receiving messages from people about "no audio" after install JamTaba. My response is just: "Please install ASIO4ALL".  Some people can`t realize by themselves about ASIO4ALL instalation I think allow other audio APIs will add more problems than solutions.

**Comment by jonjamcam** [comment]
@elieserdejesus I know this is the argument from an old discussion.

Remember that Jamtaba can be used with any driver already if used as a vst plugin (i.e. reaper). 

The asio limitation is pretty annoying for non windows users because sometimes you don't have an alternative as with linux when using wine. Wineasio is a pain to get installed in some linux distros.

Using wasapi would solve this specific issue, but the argument still stands from years to date: why force real-time usage in a non realtime environment.

We had this discussion some time ago https://github.com/elieserdejesus/JamTaba/issues/522#issuecomment-296367293 and I believe now that windows 7 is no longer supported by Microsoft it's much more relevant as many (me included) are migrating to linux.

**Comment by jonjamcam** [comment]
Obsolete...closing
