### ISSUE TITLE
Jamtaba kicked me out!

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#124]
THis just happened to me....during a jam.

![kick1](https://cloud.githubusercontent.com/assets/15310433/11104143/a5c208c0-88a5-11e5-8b8b-183cd70bae21.jpg)

then...
![kick2](https://cloud.githubusercontent.com/assets/15310433/11104155/b1bee59e-88a5-11e5-9bd5-0bbcee4bd7ce.jpg)

then it just dissapeared....not the usual crash...

I checked and the 2.0.5 is released in the page. Could that be?

Well I upgraded and It won't start. Same two messages again. :(

Tested both standalone and Vst and both have the problem

**Comment by Ezeer** [comment]
The message also is hilarious : Your version is not compatible with previous mean that this version
is superior , and that's the problem . Then you are asked to download a newer , superior +1 !
mwah ah ah .... twilight zone past 8 minutes here .
lol

**Comment by jonjamcam** [comment]
This bug is kind of similar to the rooms dissapeared bug https://github.com/elieserdejesus/JamTaba/issues/92

Only detectable when there's an error in a remote server

**Comment by jonjamcam** [comment]
lol ^^^^

**Comment by elieserdejesus** [comment]
The server quota was exausted, too many operations in data base. This is the price os success :)
Now my credit card is in the game to add more quota in the server :(

**Comment by Ezeer** [comment]
Paypal is your pal !
![supermans_pal_jimmy_olsen_149](https://cloud.githubusercontent.com/assets/1283808/11108051/dea85a52-88e3-11e5-9391-a0f5070254fd.jpg)

**Comment by jonjamcam** [comment]
killer app!

I think it's time for the donate button too. Paypal, bitcoin.......

**Comment by Ezeer** [comment]
&& ||  start a network of Jamtaba servers ( If i create a google App from france , my server will be located in France probably , or in Europa , what is good also to reduce the latency in Jam - futur direct mode )  And could prevent that kind of server's request overflow .
Don't you think so ?

**Comment by elieserdejesus** [comment]
Ezee, google app engine is doing a lot of magic to distribute requests. GAE create new server instances to handle more requests, and the database is distributed, a lot of advantages for scalable software. Create more servers is not a good model in this case because we are reinventing the GAE structure. 

The problem about request overflow is related to my free account. In free account the quotas are small, just enough to proof of concepts. Now I put my credit card in GAE and the quotas are ridiculous big, so overflow are not a problem if you put some money. Of course I'm monitoring the server usage everytime to see possible problems and think in otimizations to reduce the costs.

I use paypal in the first Jamtaba: I receive a total of $23.00   :)

But I will consider paypal again if the costs are big. For while it's ok, we can think in money stuff in the future.

**Comment by Ezeer** [comment]
**" Now I put my credit card in GAE and the quotas are ridiculous big, so overflow is not a problem if you put some money. "**
Of course ...  If you plan to pay for the users , you will have a lot of users , lol .
But your first goal was to stay free of charges , for yourself first , then others , no ? 
Now you engage your personal funds in the project , that's cool if you like it , my idea was to
try to avoid that . ( and also because the source code is open , even the server code , so why not start to use it and deploy a Jamtaba network all around the world ? )

Perhaps you don't like the idea that people starts to run Jamtaba servers ?
If so , consider remove the server part from the hub , because you can be sure that someone will
use it one of these days .
So it is ( perhaps ) better to start to think how multiple servers could work together instead of being in competition.

**Create more servers is not a good model in this case because we are reinventing the GAE structure.**
Can you develop that , what is exactly the GAE structure and why we couldn't reinvent the bycicle ?
![11-bicycletteleonard1-21](https://cloud.githubusercontent.com/assets/1283808/11116824/4fecab90-8935-11e5-8634-e3d7d14027eb.jpg)

**Comment by elieserdejesus** [comment]
Ezee, to run a server is just create an account (for free) in GAE, download NetBeans, download the GAE plugin for NetBeans, click with right button in the project name and choose "Deploy to GAE". 

It's very simple and for me is not a problem if other people run other servers. But to use this "new server" is necessary change the client code to use this new server. And now is necessary distribute this new client for users. 

The idea of a network of servers collaborating is very good, but again, GAE do exactly this things for us, but GAE want some money. 
I agree is possible think in some model to create, for example, 5 free accounts in GAE and sum the free quotas. For example, the client can handle specific server errors to discover when the free quota was exausted and pick another server. I'm shure this works and is 100% free, and easy to implement.
But at moment I prefer spend some cents, just to see how many cents a project like Jamtaba will cost. From my side this is a little "Project Management Experiment".

**Comment by Ezeer** [comment]
Ok , it's clear now ., thanks :)
From my side , i collaborate in a local project that could grow and being massive .
It was me that pushed you to open source your code , you remember ?
I also prevented you that Jamtaba is a great project and could have been a good commercial product .
You made the choice to open it to the world , and here we are !
So for me it's logical to think about the deployment in large scale , even if it's free , Jamtaba also has
to define some rules of collaboration and usage . ( in case of a community of servers i mean )

I understand that you wear the project for years now , and that it has growned such that you are
near to a commercial patern . 
That's just an observaton , i like also being part of that experiment !
Write new parts of client code is our future anyway , lol !
;)

**Comment by Ezeer** [comment]
**Ezee, to run a server is just create an account (for free) in GAE, download NetBeans, download the GAE plugin for NetBeans, click with right button in the project name and choose "Deploy to GAE".**

@jonjamcam Dear admin of the user's manual , don't you think your users would like to know how to setup a server in detail ? You could try to torture the boss to get these details ? A massive email attack,
something like that ( also he forgot to put the manual in the 2.0.5 release , it's time to syndicate , lol ! )
![syndication_multi](https://cloud.githubusercontent.com/assets/1283808/11118046/4dca1c12-893f-11e5-85bc-24d457712a4e.jpg)

**Comment by elieserdejesus** [comment]
Ezee, I'm very, very skeptic about the "commertial" potencial of online jam sessions tools. Try convert some musician to play in ninjam servers and you will see the problem. When a musician enter in a tool to play in real time jams and see all the latency related problems he never back again.

We have many musicians around the world, using internet everyday. But we have just two real success cases in "online collaborative music tools": OhmStudio and JamKazam. And in my opinion even these guys (with strong and very good marketing) are not making real money.

So, I agree we can have a "commertial pattern" here, but I don't see (yet) a real market.

**Comment by Ezeer** [comment]
You are a kind of provider .
Your software is a client that could be always free .
But that also could be sold ( i would put 15 euros on it , no problem ).
The deal is that you give a pleasant way to use the ninjam servers , + the VST plugin that is unique .

Where the users could also pay is at the quality of the services you provide .
What we experienced yesterday is just a preview , i think we can use that reality of bandwidth/requests to imagine a free model and a premium model .

In the free model , you are free to join , but server side there are policies that restrict the logging
to preserve premium users .

Premium users should never be kicked off , because the server will always preserve room for them.
So if Jamtaba users find that it is really a nice tool , some of them will choose to be premium .
Premium could also include special features , like the audio treatment you were talking about ( low cut ) to give a brand new mix experience in the Jam .

I don't know how much it cost to pay your google account , but with 30 premium users at 1$ by month
you don't loose money ...

Well , it's just the ideas that cross my mind , and i'm not talking of a big bizness here and now , just try to find solutions that gives satisfaction to i and i , with regards to the reality of facts .

I was reading something really funny about commercial practices in the computer world .
A guy from IBM ( at the early times ) made people buy their software just to be the first to use it . ( they were in fact beta testers eh eh  )

![seeking-beta-testers-post](https://cloud.githubusercontent.com/assets/1283808/11119501/60f53384-894a-11e5-99c9-e98e4d3bb91c.jpg)

**So there is no real rules , just opportunities , and perhaps fairplay ?**

![fair-play-means-respect-1-728](https://cloud.githubusercontent.com/assets/1283808/11119594/f4efd67a-894a-11e5-8dde-f8fb12315317.jpg)

**Comment by jonjamcam** [comment]
Hey guys. Very interesting all you talk above. I expect Jamtaba to be the most loved app for ninjamers out there, but remember we are very few. 

 The ninbot page (which has been the most important ninjam site ever) has about 4000 users in total registered! These numbers will never achieve commercial success, but on the other hand, this same fact is protecting all of us and our music.

 I come from a traditional Rock band background, where we were like a close family, so I understand why musicians prefer the "offline" approach to music (I'm sure Elieser knows what I'm talking about). So when I first joined the community back in 2010 I was literally blown away by the quality of musicians. 

 Back then ninbot had no more than 1000 users and it was for me a discovery of a lifetime, so I told all my friends to join and......nothing happened. I insisted and nothing.

 Finally over the years I understood the crux of the matter as with everything else in life. It's hard for me to define it, but I will say that we will always love ninjam and we expect others to love it too, but this will not happen.

Sorry...I went into rant mode......I yield back.....

**Comment by Ezeer** [comment]
**but this will not happen.**
I think everything can change .

Jamtaba is today a client like another with something different , some little details that make all the difference . The way we play music as individuals is a thing , the way we are in a public ninjam room an other . 

How you feelin before joining a session is important, and Jamtaba is designed to help people to enjoy the Jam experience . So i am confident that with the experience of the ninjammer community , Jamtaba will become better and better , introducing perhaps new concepts .

**Comment by elieserdejesus** [comment]
Nice discussion guys! 
I remember my first experiences in ninjam. I have to learn "how play in a intervallic envinronment". Play in ninjam is different from play in recording studio, live stage, etc. When I try ninjam for the first time I was very opened for new experiences. I enter in the servers with a "blank" mind. This is the big problem in my opinion: most musicians are closed to new experiences. I feel some musicians expect reproduce in online tools the exactly experience they have in stages and other "live" situations. They expect enter in a magic software with zero latency and play your preferred musical style, with people who have the exactly same musical skills, not more, not less. We can't offer this, nobody can, is impossible. 
Another barrier I observe in my friends is the technological stuff. I have some musicians friends who I can't say "install Asio4All" because this is "too complicated". Maybe you think: ah, but this is a really dumb musician. Yeh, possibiliy :), but some of these "technological dumbies" are very very good as musicians, and we will never see these guys playing online because is too complicated, many things to install, many concepts to learn, blah blah.
Unfortunally I'm convinced the market to online jam sessions is something for a few people. 

We are touching some very good points here, and one of my preferred is "the jam experience". If we want build a very good tool (comertial or not) to play online we need ask: How the jam experience can be improved?
I think is this question everytime, and off course it's not a easy topic. But I use an approach, everytime I enter in a Jam I'm observing the problems. Let me share some commom problems:
1 - when people enter in a ninjam server they don't hear nothing, because the intervals are still downloading. So they people start playing random stuff, because they fell nobody is playing. But this is not true, in general we have a cool jam rolling, and when a new user arrive the jam is poluted by random sounds. How we can prevent this? Maybe we can set the xmit to off by default when user enter in a room, and Jamtaba will auto turn on xmit when the first intervall is received. 

2 - When users enter in a room we hear a lot of low notes in guitars and keyboards, because people are tracking the chords, and the easy way to do this is find the root/low notes of the chords. This is very very bad for the other musicians. The problem here is clear: the lack of chords, or chord progression. How we can solve this? We can bind a room with a chord progression. Each room has one chord progression. This "current chord progression" can be stored in the server. When a user enter in the room he/she will see the chord progression used by other musicians. But we need some cool (and easy to use) scheme to select, propose or vote chord progressions. A chord progression database is very usefull here. 

These ideas are not "finished", are just start points we can use to refine and think in other ways to "improve the jam experience".

**Comment by Ezeer** [comment]
These are very nice proposals elieser !
That is exactly what i was talking about , new concepts born by the experience and the observation .

**Unfortunally I'm convinced the market to online jam sessions is something for a few people.**
It is our job ( or mine if your consider my nickname ) to make the things easy to handle for non-geek.
Let me talk as a game designer , if my game is too hard since the very first seconds , users will feel
unconfortable , then quickly bored , will quit and never return .
So make the experience simple must be a target for a certain type of users .
We can imagine a starter UI and a pro UI for example ?

Keep in mind the " plug and play " design and also offer some tweaking zones for experts .

**Comment by jonjamcam** [comment]
" Maybe we can set the xmit to off by default when user enter in a room, and Jamtaba will auto turn on xmit when the first intervall is received."

This must be the best idea I've heard in a long time. What you say is completely accurate. It happened to me for months until I read the "technicals" and figured out myself.

This little things will help a lot.

 BTW Jamtaba has already change my jaming experience. Just the cirlcular metro that doesn't move all over the screen is a huge improvement! And of course the sound......When I hear the recordings, finally for me the drums sound like a CD with depth not like a cassette! LOL

I use it everyday so anything that comes to mind I'll post....working great so far!

Much thankful to both, guys for your hard work....in coding.....

**Comment by elieserdejesus** [comment]
Thanks jon, please create a new issue for us. Something like "auto disable xmit when enter in a room".
I think the best approach is auto turn on the xmit after the second whole interval is received, not the first, because when a user receive the first interval he/she is still tracking the groove or chords. So, probabily when the second interval is received the user is now playing some good music and mathing with the interval. The problem with this approach are the big BPIs. Wait 2 intervals of 64 BPI to start xmit is a lot of time, specially if the bpm is slow. Maybe something like that:
1 - BPI up to 32: enable xmit after receive 2 full intervals.
2 - BPI less than 32: enable xmit after receive 1 full interval.

What you think? I'm not shure about 32 bpi, maybe we can replace 32 bpi with 48 bpi, because sometimes people play cool bluesy jams in 48 bpi.

**Comment by jonjamcam** [comment]
This thread continues here: https://github.com/elieserdejesus/JamTaba/issues/126
