### ISSUE TITLE
Can't host a server in machine since a few weeks ago

### ISSUE THREAD

**Issue by diegux74** [elieserdejesus/JamTaba#1360]
Hi, can anyone help with this? I can't neither my musician partners.
We get "Error in UPnP protocol:UPnP device found. Is it an IGD?"
I really have no clue, any help will be much appreciated.

Thanks!

**Comment by elieserdejesus** [comment]
Hi, if was working some weeks ago we can conclude the problem it`s in your side, not in JamTaba (since JamTaba not changed in the same period).  

The error message you mentioned (Error in UPnP protocol:UPnP device found. Is it an IGD?) is related with UPnP protocol. Check if the UPnP is enabled in your internet router.
