### ISSUE TITLE
Hide translation icon in "chord progression" chat messages

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#147]
Chat chord messages are not "translationable", so the translation icon don't make sense.
Solution: hide the little translation button from chord messages.

**Comment by elieserdejesus** [comment]
done!

**Comment by Ezeer** [comment]
nice .
I'm still ahead with 1 commit , ah ah ah ....
I just saw that when a room is " crowded " , there is no more bpm and bpi displayed .

**Comment by elieserdejesus** [comment]
**I just saw that when a room is " crowded " , there is no more bpm and bpi displayed**
My logic in this case was: The bpm and bpi does not matter because you can't enter in this room".

About the commits, I use a trick: always work in very smalls issues, so I finish quick and deceive myself with the idea of productivity, ha ha. This works for me. I prefer fix a lot of little issues than work for several weeks in a jumbo feature and feel like a dumb. I think is very important break the big features in little ones to keep our mental sanity. :)

**Comment by Ezeer** [comment]
**My logic in this case was: The bpm and bpi does not matter because you can't enter in this room".**
i was sure of that  , lol  .
But human are curious by nature , and when a door is closed ....
![rambo](https://cloud.githubusercontent.com/assets/1283808/11258505/e3144648-8e59-11e5-8d7a-f9b6e29b9327.jpg)
mental sanity ah ah ah
