### ISSUE TITLE
chat no fuction on ableton 

### ISSUE THREAD

**Issue by squiergtr** [elieserdejesus/JamTaba#170]
hi  elieser  i ran a test  vst jamtaba  on  my daw ableton ver 8  win xp  and the chat was not functioning i could read from the chat but could not reply back also i try to move the gui window to the size of my likening  and it would not allow that also.. these are the 2 troubles i have found so far if and question please email me when you have the time ... and thank you for writeing a great vst for ninjam..

PS;god bless

**Comment by elieserdejesus** [comment]
Hi squiergtr, thanks for your report. I never test the vst plugin in Ableton, but we have a similar problem in Reaper in the first plugin version. 

You can't see the chat input or you can't type in the chat input? 

About the other problems you detect, I suggest create different issues here in git hub, so we can discuss the problem details with you.

**Comment by jonjamcam** [comment]
Studio One has probably the same issue https://github.com/elieserdejesus/JamTaba/issues/96

**Comment by squiergtr** [comment]
hi elieserdejesus thanks for the reply back so fast  wow ..lol  yes to the
question
You can't see the chat input or you can't type in the chat input?
the answer is both  cannot see what i am typing in the chat input  and it
do not send anything i type in the chat input .. the good news is it has
not crash and burn ..lol

if you need more info on the troubles  or help in testing  let me no
again i like too thank you for makeing such a program alot of ninjamer
from way back in 2005 was hopeing then such a progam was made

iam not a programmer but if i can help you get the the product up 100%
i be happy to help you and learn a liitle at the same time ..

god bless

**Comment by Ezeer** [comment]
We are a team composed by 3 coders + 1 tester/documentalist .
As you are not coder , you could be an official tester , no problem .
Please report what operating system you use , and don't forget to setup your logging.ini file ,
because that allow to put advanced reports in the log .
Open it , edit and change things like this : 
"jt.Ninjam.GUI=false" to "jt.Ninjam.GUI=true"
That command will make Jamtaba comment a lot more about what is happening in the Ninjam Gui part . 
BE CAREFUL : the log produced can be >50mo on a long session if a lot of .ini commands
are set to 'true ' , so use it with care . ( this prevent your hard drive to burn , LOL )

HOW TO : 
If you had a bug while using Plugin version of JTB2 , look into the PluginVst folder for the log .
If using Standalone version , the log is in the main folder .
SO : Please send us your log , just drop it in that window , you will end up with that : 
[log.txt](https://github.com/elieserdejesus/JamTaba/files/41037/log.txt)

you are blessed ! Thanks .
^^

**Comment by jonjamcam** [comment]
Cool! welcome squiergtr. You can test the next alphas and betas when they are released here:

https://github.com/elieserdejesus/JamTaba/releases

**Comment by elieserdejesus** [comment]
Fixed, tested in Raper, Cubase, Studio One and Ableton, working nice in these hosts.

**Comment by squiergtr** [comment]
thanks for the update and  too you and the family have a very happy xmas
ps:bravo to you all on the hardwork jamtaba programming  you all are the
best
with out you all ninjam would not reach the next level to music
creation......godbless

**Comment by elieserdejesus** [comment]
Thanks squiergtr, a very happy xmas to you too.
