### ISSUE TITLE
Add preferences checkbox to Remember ninjamers details

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#201]
Viotele suggest remember user mute.
Remember levels and pan can be nice too.

**Comment by jonjamcam** [comment]
yes! very good idea. Remember boost/att buttons too?

**Comment by elieserdejesus** [comment]
Yes, the idea is remember fader, boost, pan and mute. After some jams when you enter in a server with wel know guys the mix will be "perfect".

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , @Hitrate, @DoublebassOO , @MagnusDrumsTrumpet , @qulf . 

I received an email about an undesired side effect when **remembering users settings (pan, fader, boost, mute, etc.)**. I think solve this problem it's not a simple decision , and I prefer share and discuss with you (you are more envolved in last discussions). The relevant email content was:

> Hey I figured it out, jamtaba is remembering mixer settings. Anyway to make this an option in settings?  Really confused me. Also  I keep finding people Ive muted before in big jams and arent showing up when I rejoin a week later.  kinda bad for karma. I think cause muted once you might never hear that person again.

I proposed just **not remembering the mute status** (simple solution), but **he is not muting**, he is **using the fader**
> I just adjust volumes so I dont think that would help much. I think the mix feature is fine as it is, its just really important to not make it the default so people know its on.

> This week when I noticed the feature, I realized I had been blocking another guitar player for weeks.  I really felt shitty about it.

I think this is really a problem, an unexpected effect of the *remember* feature!

I think is necessary: 
1 -add an option to check/uncheck **remember user settings** in preferences.
2 - Decide what is the best default option to the **remember** check box. Keep the current behavior remembering user settings by default? Or the remembering settings will be disabled by default?

I prefer keep the current behavior (remember by default) and will be possible disable the feature in preferences. 

What is your opinion?

**Comment by Hitrate** [comment]
I think it would be nice if it automatically remembers to unmute someone you’ve muted (by muted I mean disabled transmission from) when that player makes  sound through that channel.  You see often I unmute someone by disabling their track, if for instance they have two channels but only currently streaming sound on one of them...then I’ll untransmit their no-audio channel, I’ll untramsmit the ones that have one channel and have not been streaming for a while but are still lingering in the room...but it would be nice if it the automatically started transmitting from them once they begin actually transmitting sound themselves, from their channel.... 

So in order to do this perhaps we could have 3 buttons...one for hardcore transmit on off, one for muting while still receiving their channel, so unmute/mute works still, and then a third button called “Auto transmit On/Off” where it recognizes that this channel is transmitting, but not ACTUALLY transmitting anything (not making music) this disabling the transmitted wasted signal, and then re-engaging the transmission when  the player starts playing again... that way we could also have the auto transmit button locally on our channel, so you don’t have to worry about hitting your own transmit button when you wanna take a break but stay “in the jam”.

Another point about the buttons: the -12 to +12 db burton is very obtrusive and abrupt in jumping this 24(!!) db’s ! 

Suggestion: Change it to -6db, -12db jump back to 0db, then jump to +6db, then +12db
Often 12 db is way too much, and by doing t that way you’d retain the -12 and +12 option but add -6 and +6 and avoid ruined ears by making too big a jump audio decibel wise :)

Best regards

Torben Scharling

**Comment by Hitrate** [comment]
Just to reply to your direct suggestion I agree to keep it as is but have an option to turn it off in preferences :) if you could ad a variance to that option, being only remember mute, only remember transmit state etc. that would be the bomb :)

Best Regards

Torben Scharling

**Comment by jonjamcam** [comment]
> I think this is really a problem, an unexpected effect of the remember feature!

>I think is necessary:
1 -add an option to check/uncheck remember user settings in preferences.
2 - Decide what is the best default option to the remember check box. Keep the current behavior remembering user settings by default? Or the remembering settings will be disabled by default?

>I prefer keep the current behavior (remember by default) and will be possible disable the feature in preferences.

>What is your opinion?

 To be honest I really don't see a problem with this feature. Probably it's just a little inexperience with the use of the software. My opinion is that this is solved when users are familiar with the features of Jamtaba which have become a lot! But I guess the manual is too big of a document now so it's not being read. For example this is explained in the first paragraph of the "Remote Musicians controls":

![image](https://user-images.githubusercontent.com/15310433/27520112-dff7c798-59d0-11e7-9ed9-6d624a194264.png)

 Now, if you add a preferences checkbox to solve this it makes sense if the remembering feature is disabled by default. Otherwise new users will continue to see this as a "problem" being actually a solution.

 This reminds me some discussions we had some time ago about how Jamtaba was so "different" to ReaNINJAM and this looked like a "problem" at first, but the reality was that Jamtaba was indeed solving many issues that were never addressed before.

 Most software as they become complex over time tend to introduce a popup window when first launched with random tips like "did you know that all musicians levels are saved for later use?" with a "never show again" checkbox when you are already familiar with the feature.

I'm ranting here, but these are just some ideas. I think people should understand the benefits of "all happens in the background". No messy options, just jam!

**Comment by jonjamcam** [comment]
> Another point about the buttons: the -12 to +12 db burton is very obtrusive and abrupt in jumping this 24(!!) db’s !

@Hitrate I had the same thought. There's a related issue here https://github.com/elieserdejesus/JamTaba/issues/836 specifically to address this point

**Comment by MagnusDrumsTrumpet** [comment]
here as i use jamtaba as plugin in reaper mostly the transmit is excluded from remember i tested
when i mute  mut is saved in remember so i see the track muted red butten later og the person
 thats all good maybe it helps to let it flash red that we can see and remember we had muted this track
 If i would only fade a person to silence we could also turn the colour of the track or fader to show that this is nearely silence in that track easyly 
I love the the remembering feature as it is right now )  never had a prob with it

**Comment by DoublebassOO** [comment]
Hey all )
Same for me no problem and remembering the final position  is really a
great improvement  !
having the possibitly to be optional is ok , even i will probbably never
use it ..

flashing red or grey  during the 1or 2 first minutes of the session, could
be a nice feature

And  yes, keeping it by default  is for me a good idea , so that new
"jamtaber" could discover it , even it could be confusing for the first
try.

Doublebass

2017-06-26 9:41 GMT+02:00 MagnusDrumsTrumpet <notifications@github.com>:

**Comment by elieserdejesus** [comment]
The "remember checkboxes" are available now:
![image](https://user-images.githubusercontent.com/1012741/31628561-d353017a-b28f-11e7-89d6-5a1692209381.png)

As you can see the "receive" button status is not remembered. JamTaba was never saving the **receive/others xmit** status.  I'm not shure if is interesting save the **receive** status too, we can discuss this in next versions.

**Comment by Hitrate** [comment]
Greeeat ! :) I ❤️ U 🕺🏼
