### ISSUE TITLE
Fat border when changing presets from two subchannel mode to one channel mode

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#228]
If you save a preset that uses one channel (1), then add a second subchannel (2) and finally load the first preset again (3) a fat border appears in the channel. This is solved by collapsing and expanding again the channel.

![fat margin](https://cloud.githubusercontent.com/assets/15310433/12218582/43ad30a2-b702-11e5-99ae-3a5c0627f73f.jpg)

**Comment by elieserdejesus** [comment]
Hi Jon, I confirm the bug in v2.0.10. 

I tested in the dev version here and this bug is fixed. If you have time please try compile the last version of the code to confirm if the bug is fixed.

**Comment by jonjamcam** [comment]
Hi, Elieser. ATM I'm unable to compile recent code. I did a fresh clone just now and qt gets and error:

![xtra qual](https://cloud.githubusercontent.com/assets/15310433/12219073/20657838-b712-11e5-97a0-da2e1737e56f.jpg)

It used to work fine right out of the box just adding the vst_sdk files, so to test if my QT has problems I tried to compile 2.0.10 from zip source code and it compiles OK, so I'm stuck. :(.

**Comment by elieserdejesus** [comment]
Jon, I see this problema (and a lot of others) here when I change my compiler to MingW. You are compiling in MingW, but I use the microsoft compiler because I need 32 and 64 bits. My compiler don't show these errors, but I switch to MingW here and the code is completely broke. 

I fixed the code and tested in both compilers, working ok now. 

Thanks for pointing this problem.

**Comment by jonjamcam** [comment]
It's working now :D. And the bug is gone! Good job, Elieser.
