### ISSUE TITLE
Native Limiter Implementation

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#232]
The problem of saturation appears mostly when the room is full and everyone is playing at high level. This happens as the jam develops and when it's starting to get interesting, so more participants join and they have to play loud to be able to hear themselves. That makes others rise their level and so on.

 A button could be useful (like the auto translate function is) that detects the master output peaking at 0 or -1 and decreases the level in steps of say 1 or 2 dB (to make it a smooth transition).

As a drummer when this happens I have to stop playing and lower the master with the mouse which most of the times kill the mood.

Another solution could be (for drummers) midi controlled master volume.

**Comment by elieserdejesus** [comment]
Jon, I have a related idea: a master limiter. In my opinion a limiter is a better solution because the peaks will be "smashed", and the rest of the audio will be untoutched. Reducing the master level we are reducing all levels.
     We need a way to turn on/off the limiter, because some users can disaprove, or some users are using a master limiter in your preferred DAW (very common today).
     The trick part is find a good and free limiter algorithm, but I think is not difficult.

**Comment by jonjamcam** [comment]
a limiter sounds good. What do you think about adding on or two slots for vst in the master?

**Comment by elieserdejesus** [comment]
Adding plugins in master is a great idea, I'm shure this will be very usefull and improve the general sound a lot. 

But I'm thinking here and this is related with another idea, I'm thinking in "merge" this ideas. 
I have a idea for "JamTaba" native plugins, something like the Reaper plugins. Actually, the code is almost prepared for this, because is an old idea.
The ideia is:
- create slots for plugins in master, but use a "native limiter" and maybe a "native tube simulator" by default. 
- The plugin slot accept VST plugins or Native plugins, this is transparent to users. 
- The default master plugins can be removed and replaced by VST plugins, and this will be "remembered" by Jamtaba.

A issue to think carefull is the GUI. Add slots in master in the current GUI layout can be trick if you consider the "mini mode". Just to remember myself here: mini mode screen size can grow some pixels, this can be enough and avoid a GUI redesign.

Just to member, some sources to limiters algorithms:
[http://sourceforge.net/projects/delphiasiovst](http://sourceforge.net/projects/delphiasiovst/)
[http://www.musicdsp.org/showone.php?id=274](http://www.musicdsp.org/showone.php?id=274)
[http://www.musicdsp.org/showone.php?id=265](http://www.musicdsp.org/showone.php?id=265)
[https://github.com/tomszilagyi/tap-plugins](https://github.com/tomszilagyi/tap-plugins)

**Comment by jonjamcam** [comment]
Yes, good dual design. For the record: "must" native FXs: Reverb, delay, compressor/limiter, gate.

**Comment by elieserdejesus** [comment]
Very good article about mastering and compressor + limiter, thanks!

**Comment by jonjamcam** [comment]
Harrison consoles have a really good design for compression per track:

https://www.youtube.com/watch?feature=player_detailpage&v=BDLcCtm-RJA#t=78

**Comment by elieserdejesus** [comment]
Very nice GUI ideas in this video!

**Comment by pljones** [comment]
As with a few other ideas, I'd see this living in the standalone and letting the VST input be controlled by the DAW.  It keeps the main part of JamTaba "free" of the extra bits needed by the standalone (and potentially allows that standalone component to host other things later, taking those features with it).

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
