### ISSUE TITLE
Chord Progressions/songs database

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#236]
A idea proposed by @NakajimaYusuke in #206

**Comment by NakajimaYusuke** [comment]
I have a little ideas about the format of the chord progression.
It's about the format of syncopation.
I think, if we can express the syncopation in the chord progression,
it would be convenient to reproduce the songs.

How do you guys type syncopated chords in text?

In order to express the chord syncopation,
It would be good to determine the format for that.

The following is my idea."F" is syncopated chord.

idea1
|Am  |G   (F   |E   |

idea2
|Am  |G  (|F   |E   |

idea3
|Am  |G   |(F  |E   |

**Comment by elieserdejesus** [comment]
Interesting idea Nakajima, I like the **idea 3**, it's more clear for me.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
