### ISSUE TITLE
enable and disable sync with reaper

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#237]
Hey guys)
is it possible already to switch sync on and off using Jamtaba in reaper,
 so that i can sync first and if jam is running i can put then tracks with it without disturb the jam by total resync all when using startbutton (Play) in DAW again

greets from Magnus

**Comment by elieserdejesus** [comment]
Hi Magnus, this is possible and a good idea. Scheduled for the next release.

**Comment by MagnusDrumsTrumpet** [comment]
cool thy )))

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , I do some improvemenets in the "sync with host" feature, but is not perfect.
Jamtaba still restart the interval when the button "play" is pressed in the host, but the last downloaded (and not started yet) interval from each musician is preserved. But sometimes we have downloaded just one interval from some musician, so is not possible preserve "half" interval.

I tested REaninjam and see the same behavior, Every time we press the "play" button in Reaper the jam audio is affected. 

The problem is related with how VST plugins and hosts are comunicating. When we press the play/start button in a DAW the VST plugins are *suspended** and **resumed**, in this exact order. But plugins are suspended when you deactivate or delete the plugin too. So, **suspended** means "clean all the stuff, because this plugin will not be used in this moment". If you activate the plugin again this plugin is **resumed**.
Every time Jamtaba Vst plugins is **suspended** all stuff is discarded, JamTaba is "reseted" because this is the expected behavior when a plugin is suspended. For example, if you turn off the plugin in your DAW the expected behavior is "clean all the stuff", right? The problem is some VST hosts (like Reaper) are suspending plugins every time we press play/start, so these DAWs are reseting all the stuff. 

I have an idea for a workaround, I'm creating a new issue #246
