### ISSUE TITLE
qt compile errors

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#247]
Qt is showing some compile errors now.

![qt error](https://cloud.githubusercontent.com/assets/15310433/12533924/207f21b4-c222-11e5-9dc3-f29674b9fbef.jpg)

**Comment by elieserdejesus** [comment]
Jon, I switched to mingw compiler here and is working fine.
The problem is your QtCreator is using old files, and these files are conflicting. This happens here sometimes too.

The solution is run a "Clean" command (right mouse button in the project name). This "Clean" command will delete the compiled files. Next time you compile all the files will be generated from scratch and working.

If not work try execute the command "Run Qmake" (use right mouse button too) before clean.

If not work try the command "Rebuild". This will force the recompilation of the entire project and will discard old/conflicting stuff.

If not work (hehe), delete the compile dir manually, this will force QtCreator to generate all stuff in the next compilation.

**Comment by jonjamcam** [comment]
clean worked. thx. :D
