### ISSUE TITLE
Server disconnects if some special characters are used in the insrtument box

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#294]
I tested this with some accented letters like Á, ü, á. Looks like the server rejects this kind of characters if used in Jamtaba. This is important in relation with the internationalization feature because new users that use almost any other language than except English will be tempted to use this letters (or others) and will get a disconnection.

I tested Reaninjan on this issue and there's no problem of disconnection there:

![image](https://cloud.githubusercontent.com/assets/15310433/14386382/e0874f66-fd7a-11e5-9c60-fc9341b65db1.png)

When this type of characters are used in reaninjam, they appear in Jamtaba wrongly decoded, but test with two instances of reaninjam  is necessary to check.

NOTE: Jamtava VST 2.0.13 used to test

**Comment by teamikl** [comment]
@jonjamcam 

about the disconnection behavior, should be fixed.

about the decode issue,
This change was added my patch #160 and the details #159 

Unfortunately there is no perfect solution on JamTaba side.
it's because NINJAM protocol issue, they does not have encoding info, and
official standalone client and reaninjam on windows use their native encoding.

it's possible to pass the situation you reported, but then that patch will occur other side problem.
e.g. for this case, decode as local8bit can be the solution for windows, but not for mac.
this is happen even between official clients, not JamTaba specific problem.

decode received text still has ad-hoc solution by detect charset.
but encode send text has no ways.

NINJAM protocol should support encoding and all clients have to update to follow the protocol.
it's hard tasks.

**Comment by jonjamcam** [comment]
@teamikl So a simple solution is to allow only letters with no special characters.

**Comment by jonjamcam** [comment]
This strings DO work in isolation, but some combinations of them will trigger the disconnection:

! " # $ % & / ( ) = ? ¿ ¡ \ | ° ¬

for a quick fix I think only accept ASCII codes:

from 48->57 (numbers 0-9)
from 65->90 (letters A-Z)
from 97->122 (letters a-z)

![](http://www.asciitable.com/index/asciifull.gif)

what do you think?
 
'

**Comment by teamikl** [comment]
@jonjamcam 

as quick solution, I think just add fall safe logic
make the program not disconnect by failed decode, 
instead of change encoding to pass the decode.


Encoding is a deep problem in NINJAM,
accept ASCII only will be problem for multi bytes charset :(

for recv I have idea for adhoc patch (but not easy)

(win reaNINJAM) - server -> (win JamTaba) client can detect encoding here

and for send, this can't fix in JamTaba side.
(win JamTaba) -(what encoding should send?)-> server -> each clients

if win/JamTaba encoding become compatible with win/ReaNinjam then still problem
that may NOT work for these cases, need research mac 's local8bit encoding on qt
- (win JamTaba) - server -> (mac JamTaba)
- (win reaNINJAM) - server -> (mac JamTaba)

my opinion
support windows's native encoding make situation more complex. (more bugs on another cases)
because reaNINJAM/win encodings are not one. each countries use their own charset.

**Comment by teamikl** [comment]
@jonjamcam 

Another solution, if anyway JamTaba should have the way then
change encoding options for advanced users.

Although, I want everyone use UTF-8 its the ideal solution for this.
(can make program simple then drop support/maintenance costs for each combinations of encodings)

**Comment by teamikl** [comment]
as quick fix, I will work for this first.

- [ ] safe logic for decode track name, fix the disconnection behavior

**Comment by teamikl** [comment]
@jonjamcam 
I am testing this now, I had misunderstand a point

the disconnection was when those character input into the instrumental box on JamTaba ?
Here ASCII only could be the quck solution, maybe some validator for the instrumental box.

**Comment by teamikl** [comment]
more debug info

Input those special characters before connect to server
then connect to NINJAM server made program crash at win8.1/mingw32/debug

- [ ] for LocalTrackView, validate the user input (and also load from config file)
- [ ] NinjamTrackView need to test if remote ninjam clients send such special characters

**Comment by teamikl** [comment]
@elieserdejesus 
I figure out this problem, it's NINJAM protocol
ClientMessage's payload is count with QString::size but the real payload is QString::toUtf8().size()

another places which use QString::size for payload counting also may have the same issue?

**Comment by teamikl** [comment]
@jonjamcam 
I think we can take another solution

at least the disconnect by those special characters should be fixed in this issue,
it's high priority task.

as the result, how those characters are shown another side, not sure, need test.
I don't know much about those extended latin characters.
maybe another letters are shown if they use different charset.

about showing those all letters correctly on another clients side.
won't be fix, because each clients assume their own encoding.
(e.g ReaNINJAM/mac may show utf-8 correctly, but ReaNINJAM/win not)

**Comment by jonjamcam** [comment]
> the disconnection was when those character input into the instrumental box on JamTaba ?

@teamikl yes. If you type them before entering a server, the server will reject the connection. And if you type them once you are inside the server (assuming they were not used when connecting), you will be disconnected after the next bpi cycle starts. .

**Comment by teamikl** [comment]
@jonjamcam 

OK, that I met crash was because debug build.
there was assertion check which enable only debug time.

Now I push the fix patch, can you test this branch
[teamikl:fix-server-disconnect-by-special-chars-channel-name](https://github.com/teamikl/JamTaba/tree/fix-server-disconnect-by-special-chars-channel-name)

need review and test before merge.

**Comment by jonjamcam** [comment]
@teamikl Sure I test., but how do I import this branch into my fork? I normally import eliser's commits. Do I change the remote to piont to your fork?

**Comment by jonjamcam** [comment]
@teamikl I change the code manually and tested. It's working! I'll test more intensely during the day. Good job!

**Comment by teamikl** [comment]
@jonjamcam 

Thx for test. yes, you could do that manually this is short patch.

This is Git topic, simple way you could clone my fork repo and checkout the branch.
or using Git way, you needed to add my fork as remote.
the local repo can have multiple remotes. then fetch remote (download)
and checkout remote branch. I will explain the detail if next chance.

it's useful if you can use Git, you will no need to make many copy folders,
git can switch the working context by change the branch.

**Comment by elieserdejesus** [comment]
The fix is integrated in master now, thanks @teamikl and @jonjamcam, very cool work!

**Comment by jonjamcam** [comment]
> his is Git topic, simple way you could clone my fork repo and checkout the branch.
or using Git way, you needed to add my fork as remote.

@teamikl OK. I understand now. I'm getting used to the Git console use little by little. Thx.
