### ISSUE TITLE
Implement a "Mute Chat" button

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#306]
![](https://plnami.blob.core.windows.net/media/2015/03/troll031615-800x500.jpg)

I'm thinking about a simple and fast troll block button. The idea is that when a troll is detected in a room (chat only or chat/track) we can make him vanish locally (from our client only) so his audio/chat doesn't bother us anymore .The problem with trolls is that they tend to tarnish the mood and break concentration and focus, so my approach is to have 2 levels of banning.

1.- light: The chat is put on dark color and the channel is grayed out and muted for the ongoing session only.
2.- full  : the chat/track is not shown for this individual anymore (including future sessios) until the user unbans him willingly (i.e. opening a menu, or something).

Before I go on I want to ask you @elieserdejesus and @teamikl if you think this is an important topic to adress in the Jamtaba implementation or not?

**Comment by elieserdejesus** [comment]
@jonjamcam , personally I never had problems with trolls in ninjam. But we known very well the ninjam troll legends :) And we have another cases every time related in ninbot forum. Sometime ago I have a similar idea to block the "troll" messages in chat. In general I think this is a "sad feature", but I have to admit this will be usefull for many ninjamers. 

I think we can discuss this feature. Spend time discussing "trolling" It's not my preffered topic, but it's necessary :(

About implementation details: we need block the user using the USER IP. But a "true troll" knows about proxies, and we are blinded again if the IP is different. It's impossible block a smart troll :)

**Comment by teamikl** [comment]
@jonjamcam 
it's difficult for NINJAM public servers. because the most users are anonymous.

>  a troll is detected in a room (chat only or chat/track) 

e.g. if long loud noise was detected as troll action,
but if it was unexpected behavior by new comers with wrong setting,
they does not know how to setup yet.
someone should support or they may give up to use the software.

> his audio/chat doesn't bother us **anymore** .

How to Identify the troll user?
they can type any name and IP address may be changed.

use IP address for identify has rare issue,
it's because the last field is masked,
different people who live in same building had same address string.
If the troll spoof other user and get banned intentionally... should avoid that.


I can understand the case you may assume, someone who muted(or uncheck recv)
but they try reconnect (mute will be unchecked by reconnect).
There is no perfect way to block them, but still there are several useful cases.

**Comment by jonjamcam** [comment]
@teamikl 

> different people who live in same building had same address string.
If the troll spoof other user and get banned intentionally... should avoid that.

true.

@elieserdejesus I'm glad you didn't have to go through this :D.

So in my experience a troll is not someone who plays a super distorted guitar during a jazz jam. That's more muisc experimentation and in that case if you don't like it you have the mute button.

 For me a troll is someone who is constantly chatting(or speaking) thing diverting attention to fights, insults, etc. It's funny but from what I've experienece a chat troll is a lot worse than a audio troll because the chat is needed for commenting and it0s very important. If you see insults there your attention is diverted.

So I think a "chat mute" option could be enough to start. I suppose it's not that hard to code. We could test on future releases and see the feedback.

**Comment by elieserdejesus** [comment]
+1 for "chat mute". It's not difficult to implement.
