### ISSUE TITLE
Test the 2.0.14 pre-release

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#345]
@jonjamcam and @teamikl , please check the releases, I uploaded the 32 and 64 bits pre-releases.

Let's test these releases before launch the new version officialy!

- [x] Update screenshots in jamtaba.com
- [x] Update screenshot in README.md  (using the same image url?)
- [x] Fix linux installers (working in #360)
- [x] Put a link for linux 32 bits installer in website.
- [x] Test themes in Vst Plugin

**Comment by teamikl** [comment]
@elieserdejesus 
Ok, look like v2.0.14 has a lot features implemented. I will read ChangeLog
do you have an extra check list for test detals? or just test play as usual jam?

**Comment by teamikl** [comment]
found 1 issue now, about [T] button translation (for Japanese). I will make a report

**Comment by teamikl** [comment]
@elieserdejesus 
I made PR #348 for the fix

**Comment by teamikl** [comment]
@elieserdejesus 
Question, about ChangeLog said
> Release for Linux 32 bits too (the 64 bits was available in the last version).

where is the downloadable binary for linux 32bits? 
and need to update "./lib" (which downloaded from dropbox) if want try linux 32 build ?

**Comment by teamikl** [comment]
I found the info, linux 32 issue was moved from 2.15 to 2.14 and #314 still open.
so it was the last issue for the next release

**Comment by elieserdejesus** [comment]
@teamikl 
> extra check list for test detals? or just test play as usual jam?

no extra check list, just a "play" test to have some fun :)

> where is the downloadable binary for linux 32bits? 

Not available yet, I will compile and publish the release soon. 

> and need to update "./lib" (which downloaded from dropbox) if want try linux 32 build ?

Yes Tea. The pre compiled libs are updated in dropbox to include linux 32 bits libs.

**Comment by teamikl** [comment]
@elieserdejesus 
played 64bit/win8,1 standalone, it works fine.
I am not VST/MIDI user, so I did not touch them at all.

one point I noticed
channel name I had "Your Channel" from previous settings.
that could be empty and show placeholder text.

I had user name "test", name filed could not be empty
when remove all letters it restored previous name. is it an expected behavior?
as user view point, I wonder why there no placeholder for name.

**Comment by elieserdejesus** [comment]
@teamikl 
> channel name I had "Your Channel" from previous settings.

The "Your channel" name was stored in your json file? If yes this is the expected behavior. 

> when remove all letters it restored previous name. is it an expected behavior?

Yes Tea, at moment this is the expected behavior. I'm using a custom QLineEdit to store the last "valid user name" and use this value when necessary (invalid user names, like empty names). I think this can be changed to allow empty names **in the QLineEdit** to use the placeholder text. The code is checking for empty names before connect in servers, if the name is empty a input dialog will appear asking for user name.

Tea, can you code this feature (allow empty user names )? If yes please check the class **UserNameLineEdit**.

**Comment by teamikl** [comment]
@elieserdejesus 

> The "Your channel" name was stored in your json file?

Yes, in previous json. this is ok.

about user name
does not allow the empty name set "anon"?
If it require input name then how about disable enter button with UI?

If it was connection event timing, event handler will have the name check code?
modal dialog inside event will block UI's event loop. or we must take async approach.

I can suggest implement this with statemachine class, I will make WIP PR

1. when user name is empty
  - disable server connect menu and enter button
  - show info message on status bar (or somewhere user notable info field)
    - eventually this will add new translatable text resource (so .. plan next version?)
2. when user name is valid (not think invalid case tho, since not allow the input)
  - enable server connect menu and enter button
  - reset the info message

**Comment by elieserdejesus** [comment]
@teamikl 
> does not allow the empty name set "anon"?

I'm not shure if I understand. Can you ellaborate?

> If it require input name then how about disable enter button with UI?

I think this will be very confuse to new users. New users will take some time until discover the enter button is disabled because the use name field is empty. I'm thinking in the situation where a new user install Jamtaba, can't enter in any server, and quit. 

I vote to keep the current behavior: ask user name when trying to connect AND the user name is empty.

> If it was connection event timing, event handler will have the name check code?

If I understand correctly the answer is **yes**. I'm using the simple approach: modal dialog blocking the events (if I remember correctly).

**Comment by teamikl** [comment]
@elieserdejesus 
I mean the first line, empty name will be "anon" as usual in NINJAM.
if not allow the default name for empty name field, then no need to be empty.
(I think ninjam server set the default name)

my point is
1. channel name can be empty 
2. user name can't (except the first time running)

when focus was out restore name automatically is not a common user experience.
unless they know the spec this field is necessary, users may not know what happen.
(show short warning message here may help)

> I think this will be very confuse to new users.

I agree your point for the first users. that should be improved for the case.
I was going to say that on _"show info message on status bar (or somewhere user notable info field)"_

>  I'm using the simple approach: modal dialog blocking the events (if I remember correctly).

it's ok as quick simple solution, but there are implementation issues

- if user see the empty name field only the first time  
  it's rare situation, if here had issue but may not be test enough.
- side effect of block main event loop ... it's safe? it's up to how program designed  
  e.g. timer event may be blocked etc.

you may know whole JamTaba code, you may not care this if you know the effect was small.
For me it's different position, I don't know what happen as the side effect. so it's risky.

another point in implementation, I worried two place to inputs
make maintenance cost twice. this sometime make the situation
like, it's ok in name field directly, but not from input dialog.


about the name input dialog, it was confuse for me

- when user click enter button, user expect behavior is enter room.  
  (at this point, I am not new user, I know other clients and use default name "anon")
  e.g user input web form, user clicked submit button, but it report name field was missing.
  modern form guides user follow correct steps before enter.
- user will learn the name input dialog because there was no name yet
- second time, they may expect enter with new name. but no name input dialog
  they will learn because that time they had saved name.
  if name was empty then got name input ... but how to make name field empty.

we can delay this discussion for next version? I can code for demonstrate.

**Comment by elieserdejesus** [comment]
@teamikl 
> my point is
1. channel name can be empty 
2. user name can't (except the first time running)

Exactly!

***
> when focus was out restore name automatically is not a common user experience.

I agree, it's not intuitive. I think this is another bad idea I had :) The simple solution is just change the class **UserNameLineEdit** to allow empty names. Allowing empty names the placeholder text will appear. If user keep the name empty and try to connect in a server the input dialog will appear asking the name.

***

> I was going to say that on "show info message on status bar (or somewhere user notable info field)"

I'm not a huge fan of status bar, I think (almost 100% shure) people don't read these stuff. And in my opinion people are right. We need design "text explanation free" UIs. It's not easy, but is possible. 

***

> I'm using the simple approach: modal dialog blocking the events (if I remember correctly).
side effect of block main event loop ... it's safe? it's up to how program designed
e.g. timer event may be blocked etc.

Tea, the side effect is small. Two things in my mind here. Let's consider the user name is empty and the input modal dialog will appear in these scenarios:

**1 - User is listening a public server and try to connect.** 
      
1.  The waveform animation will stop, it's ok, expected behavior.
2.   the public servers list will not be updated anymore because the event loop is blocked, no more requests to jamtaba server asking a new public rooms list. It's ok too. Buttttttt, if user wait a very long time to type the user name the jamtaba server will not receive the periodic "I'm alive" message, and will disconnect the user. Jamtaba client will not close, but the public rooms list will not be updated from this point.

**2 - User is playing in a server and try connect/jump in another server.**
     *Side effects*: If user is playing in a server so the user name is not empty, and the input modal dialog will not appear. No side effects in this scenario. 

***

> another point in implementation, I worried two place to inputs make maintenance cost twice. this sometime make the situation like, it's ok in name field directly, but not from input dialog.

Tea, all user name validations and rules are coded in the class **UserNameLineEdit**, inheriting from **QLineEdit**. The same class is used in user name input (main window) **AND** in user name dialog. The code is not duplicated, we are using 2 instances of **UserNameLineEdit**.


***

> about the name input dialog, it was confuse for me
... if name was empty then got name input ... but how to make name field empty.

I agree, it's important allow empty user name. I propose the solution described in my first response in this message. Just change the class **UserNameLineEdit** to allow empty user name, it's a 5 min solution.

**Comment by teamikl** [comment]
@elieserdejesus 
Thank you for that long information. I try reduce key points
__allow empty user name__ and __user name dialog__

> UserNameLineEdit to allow empty user name, it's a 5 min solution.

This is ok. let make this first.
Do you mean here just change the validation regexp to `[a-zA-Z0-9 _-]{,16}` ?
(and drop lastValidUserName if no more need)

about user name dialog, this is another topic. when dialog return empty name
cancel connection or allow send empty name to server. (will be named "anon" by server) ?

about validation code encapsulated in a sub class is ok.
my point here was refactoring topic (can be skip).
it's two instances make two situations here, usually this easy to make untested situation.
I think this is low priority stuff, it's rare to see that dialog.  now let's continue another topics for v2.14

**Comment by teamikl** [comment]
> Do you mean here just change the validation regexp to [a-zA-Z0-9 _-]{,16} ?

was not enough, I will work on this.  @elieserdejesus  is it safe to remove focus event?

**Comment by elieserdejesus** [comment]
> Do you mean here just change the validation regexp to [a-zA-Z0-9 _-]{,16} ?
(and drop lastValidUserName if no more need)

Exactly Tea, this was my initial idea too.

> is it safe to remove focus event?

Yes, please drop this event. I use the focus event just to restore the "lastValidUserName".

> about user name dialog: when dialog return empty name cancel connection or allow send empty name to server. (will be named "anon" by server) ?

I prefer **disable the ok button if user name is empty**.

**Comment by teamikl** [comment]
@elieserdejesus or @jonjamcam 
the screenshot on jamtaba.com and README.md also update?
It's what new users will see before install, that was now outdated.

I was going to take, but no one active now.

**Comment by elieserdejesus** [comment]
@jonjamcam  and @teamikl , finally all tasks for 2.0.14 are done. 
The 2.0.14 is released, site updated, etc. This release was a very intense round for me, I will be retired for some days, I really need take some rest.

Thanks for all your help, I will back in some days!

**Comment by jonjamcam** [comment]
You deserve it, man. Have a nice time.
