### ISSUE TITLE
instrument name placeholder needs pencil to be intuitive

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#352]
To keep up with the design,,,

![image](https://cloud.githubusercontent.com/assets/15310433/14868807/fb6f0ea6-0ca5-11e6-8ce5-1fc473186abf.png)

I think a little smaller could fit ok

**Comment by elieserdejesus** [comment]
@jonjamcam , I have a big problem with this idea:

I spend too much time working in this pencil icon to get every pixel available for the user name text. Was a pain. It's not the kind of tasks I appreciate. In the channel name the situation is very bad, because we have the wheel icon. We will end with almost no horizontal space for the channel name text. 

I agree the text fields are not matching, but I can't see a better UI with 2 pencils. Honestly, I see a better UI (more clean) without the pencil.

**Comment by jonjamcam** [comment]
Sure. No problem. I thought i was simple thing to do. closing....
