### ISSUE TITLE
Add emoticons to the chat

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#361]
I think this implementation could be a lot fun for users. Is it a possibility?.

![image](https://cloud.githubusercontent.com/assets/15310433/14934096/3e575bc4-0e7c-11e6-90a8-9cc29481c705.png)

http://library.blackboard.com/ref/8fb6da4a-0569-4d9e-89f3-c32ec8370cd9/content/moderators_and_participants_guides/chat/adding_emoticons.htm

**Comment by teamikl** [comment]
I had snippet in JS. https://github.com/teamikl/ninjam-chat/issues/15

I have two topics
- non-Jamtaba users and people who had not use those emoticon, they may not understand the plain text.
- we have to consider the side effect, Chord progression detection on chat text.

instead of (y) and (n), there is a popular notation for emoji. it's like
```
  :thumbsup:
```
long typing? then need completion support.
you can see that on github issue comment here, type : and something, you will see the icon preview list.
user action will be type : for starting insert and just select from drop list.
If it ok to be v2.15.0 then I can work this task. vacation here

**Comment by elieserdejesus** [comment]
> If it ok to be v2.15.0 then I can work this task. vacation here

Shure Tea, please add this cool feature. I'm scheduling for 2.0.15.

**Comment by jonjamcam** [comment]
cool!

**Comment by teamikl** [comment]
This is an interim report. I am testing this as local standalone project.

![screenshot 8](https://cloud.githubusercontent.com/assets/146129/15138674/64230558-16cc-11e6-8c84-de3169c3820c.jpg)

current satatus is, I still need to research for customize Qt's completer.

- [ ] completer show the list with preview icon  
  set the custom view by http://doc.qt.io/qt-5/qcompleter.html#setPopup
- [ ] customize completer behavior  
  default behavior of completer required exact match, could not use completer in middle of text.  
  I am trying http://doc.qt.io/qt-5/qtwidgets-tools-customcompleter-example.html
- [ ] resize icon (resize by stylesheet in QTextEdit did not work)
- [ ] enter key on completer triggered returnPressed event.
  this make duplicate send message twice.
- [x] collect images from https://www.tortue.me/  
  same image used in github issue message :koko:  
- [x] generate resource list (as sample image for test)  
  this moment, that generate script only, no redistribute images  
  https://gist.github.com/teamikl/810fc06b15e410e882b8278f579a3b30

Emoticon support without the custom completer,
I can implement soon but `:thumbup:` notation it's long for typing.
I will report the progress on this thread, and will make PR when integrate into JamTaba.

**Comment by elieserdejesus** [comment]
@teamikl , very nice news!

**Comment by teamikl** [comment]
I made PR #376 
I will separate the task about completer. that would be another PR.

**Comment by elieserdejesus** [comment]
Nice @teamikl , I will check the PR soon.

**Comment by jonjamcam** [comment]
> long typing? then need completion support.
you can see that on github issue comment here, type : and something, you will see the icon preview list.
user action will be type : for starting insert and just select from drop list.

 @teamikl @elieserdejesus What do you think about a button to open an emoji keyboard like in phones?

- ![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/iphone6-ios9-1-messages-emoji.jpg)

https://support.apple.com/en-gb/HT202332

The emoji bar can be placed just above the chat  input box for example:

![image](https://cloud.githubusercontent.com/assets/15310433/15227818/5ff45998-185f-11e6-8343-89fe18bc3fbb.png)

**Comment by elieserdejesus** [comment]
> What do you think about a button to open an emoji keyboard like in phones?

@jonjamcam , I think this is a very good idea. My suggestion is just but the emoji bar in bottom, because the emojis are less used than text input field.

**Comment by teamikl** [comment]
popup direction should be bottom? or dialog?
I don't know how wide size the icons table will require, yet.

I scraped http://www.emoji-cheat-sheet.com/ and made category list in json format.
that had five categories

| Category | number of icons |
|:------------|--------------------:|
| People | 193 |
| Nature | 115 |
| Objects | 260 |
| Places | 106 |
| Symbols | 202 |

each icon size are 24x24 (original size was 64x64)
This is a preview in local test project, JamTaba chat area is more narrow than this.

![screenshot 1](https://cloud.githubusercontent.com/assets/146129/15234072/c6b23a36-18e8-11e6-9a1c-e21f672d4217.jpg)

NOTE: you can see some cell are missing,
it was because of the scraping category and fetch icon file another site. need to check this more.

----

There was another approach to input, that use unicode emoji character.
If your system had font then can show this 🎸☺
I have inserted gutiar and smile character in unicode, not `:guitar:` notation.
input method support the typing and lookup. (but most users does not notice, so useless)
about the guitar ison seem github convert the unicode emoji data to icon.

- http://unicode.org/emoji/charts/full-emoji-list.html
- http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by elieserdejesus** [comment]
> popup direction should be bottom? or dialog?

I think bottom is ok. I thinking in something like the QComboBox popup. I'm shure if we are talking about the same idea :)

**Comment by teamikl** [comment]
https://www.dropbox.com/s/qvp75w03iid4hdl/TestEmojiList.zip?dl=0

- [x] categorize
- [x] exclusive category selection
- [ ] hilight selected category (testing stylesheet now)
- [ ] popup
- [ ] redesign class to emoticon selector widget  
      QCompleter use model/view for this.

BTW, another topics
NINJAM has several client implementations.
and the emoticons feature will be only available in JamTaba at the moment.
Users who use another client will see raw notation text, is it ok?

**Comment by jonjamcam** [comment]
> Users who use another client will see raw notation text, is it ok?

That's the case, unfortunately. One solution though for some kind of compatibility is to have a standardization like I posted before:

![](https://cloud.githubusercontent.com/assets/15310433/14934096/3e575bc4-0e7c-11e6-90a8-9cc29481c705.png)

but this is only partial solution

**Comment by elieserdejesus** [comment]
> Users who use another client will see raw notation text, is it ok?

Ok for me. It's almost the same with chord progressions. Non Jamtaba users will see just a text when other users send the chord progression in the chat message.

**Comment by elieserdejesus** [comment]
finishing the implementation in https://github.com/elieserdejesus/JamTaba/pull/973

**Comment by elieserdejesus** [comment]
implemented in https://github.com/elieserdejesus/JamTaba/pull/973
