### ISSUE TITLE
Write "clipsort.log" rather than "Reaper project.rpp"

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#378]
The current "Reaper project.rpp" is very unweildy for a jam of any length as each interval is a separate audio segment for every participant.

ReaNINJAM creates a "clipsort.log" file (simple plain text format) that Reaper natively knows how to parse, resulting in merged audio segments, which makes subsequent editing much easier.

Using "clipsort.log" would add an additional step at the end of each interval (to log the clips for that interval) but that would be minimal overhead as the individual audio files are already being written as is the "Reaper project.rpp".

It would also require writing interval files into the same structure as Reaper's clipsort.log parser expects but the existing Reaper Project Generator can be amended to deal with that.

**Comment by elieserdejesus** [comment]
Hi @pljones . I decide not use clipsortlog few years ago because I feel it's a "hidden" feature in Reaper. It's definitely not intuitive for common users. Generate DAW project files make more sense for me. For example, I see some Cubase users playing in Jamtaba, and maybe it's time to write a **CubaseProjectGenerator** class. 

When opening a clipsort log you are asked to join or not the audio segments. If you choose "no" you will have a lot of splited audio segments, and in this case the .rpp generated by Jamtaba and the clipsort.log are similar (splited audio segments in both). I think you are interested in "join audio segments". So we have some possibilites

1 - Put something like a "join audio segments" check box in Jamtaba **Record preferences**. Still generating a .rpp file, but using merged audio segments.

2 - Generating a .rpp AND a clipsort.log and put checkboxes to each option in Record preferences. Maybe people are interested in just one possibility or in both. In Record preferences we will see 3 checkboxes, for example: 1) Generate common Reaper project file; 2) Generate clipsort.log file for Reaper; 3) Generate Cubase project file.

3 - I think **1 & 2** can be combined, because people can choose any option described in **2** and select or not the option to **join audio segments**. For example, I can chosse only **Generate Cubase project file** and check **join audio segments** to achieve a Cubase project using merged audio segments.

I think is very important keep the **splited audio** possibility. If you are editing a jam and the goal is keep the things "real" (preserve the original jam) is better work with joined audio segments. But sometimes the idea is generate a "fake" (but good) song, and splited audio is better because is easy identify and remove/reorder "dead/useless" segments. If the jam is **chord progression based** is easy change the order of splited audios to achieve better (more musical) results. For example, it's easy solve the common "cross over solos" problem. Just keep one solo and move the "cross overed" solo for the next interval.

**Comment by pljones** [comment]
It's not all that hidden - "Open Project" dialog includes "clipsort.log" as one of the file types :).

Note that the interval-based structure of clipsort.log is at odds with the track-based structure of the RPP file - i.e. each interval has a collection of audio files, rather than each track having channels which have a collection of audio files.

Thus clipsort.log is closer to "what happened" than the track-based approach of ReaperProjectGenerator and the support for this in JamRecorder.  It is just a straight record of the intervals and the audio chunks as they arrived, without even trying to work out a "track and channel" structure.

ReaperProjectGenerator has another problem in that it sets the time signature to 4/4 regardless.  This might be wrong - imagine an interval is 21 beats long because it's three bars of seven beats!  clipsort.log just records the interval length in beats and Reaper parses this into the bar length.  That makes it very easy to split and reorganise the merged audio should it be necessary (which is rare).

I've actually got quite a long way writing the ClipSortLogGenerator code - I had to write a JamInterval class and add a QMap to Jam, so JamRecorder has a fair number of changes as the existing code made many assumptions about what it was going to be used for (which is fair).

My plan was to add clipsort.log as an addition option when recording.

I'll probably have a pull request ready tomorrow.

**Comment by elieserdejesus** [comment]
> I've actually got quite a long way writing the ClipSortLogGenerator code 

Nice news @pljones . I wroted these classes some time ago, and never look again. So feel free to propose design changes and improvements. 

The only point we have to take care is: keep the possibility to write "project file generators" for other DAWs than Reaper. I
