### ISSUE TITLE
MAC OSX 32 bits version

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#41]
I was able to compile in 32 bits in mac compiling Qt in 32 bits. But VSTs don't work. Something related with CArbon. Qt 5 don't use Carbon, Cocoa is default.

**Comment by Ezeer** [comment]
Good to know .
I keep an eye on that for the minimum specs requirements for mac ( see FAQ ) : 
https://github.com/elieserdejesus/JamTaba/wiki

Also , what about the Linux port ?
I've seen that : 
http://doc.qt.io/qt-5/linux.html

We could try to recruit for Linux ?

**Comment by elieserdejesus** [comment]
Ezee, I try Jamtaba in linux some months ago. Just install Qt for linux, install QtCreator and "bangg", you are able to compile Jamtaba. But I quit for while because I have many problems with file names. In some piece of code the include is "SomeFile.h" but the file name is "someFile.h". Linux can't find the file, but windows and Mac don't have problem.  But I think is not difficult write a port for linux. We just need tweak some thinkgs in PortAudioDriver, and maybe recompile some lib (rtmidi is not compiled yet for linux).

**Comment by Ezeer** [comment]
*Linux can't find the file, but windows and Mac don't have problem.*
well , we'll have to write portable code so .
I think to install linux too , perhaps you could help me for that too ?
( choose the distro , install under windows etc ...)

**Comment by elieserdejesus** [comment]
Ezee, at moment the code is 99% portable. In some places we have #ifdef WIN32  stuff, but these codes are well isolated. So the portability is not a big issue.  I run my tests and compile the linux libs using Ubuntu in a virtual machine (I'm using VirtualBox).

**Comment by Ezeer** [comment]
**Ezee, at moment the code is 99% portable.**
I see , that is again very good .

I'll check virtualbox , thx !
And for the VST problem for mac.... found that in case : 
http://www.synthtopia.com/content/2012/12/28/free-app-lets-you-run-windows-vsts-in-your-mac-daw/

**Comment by elieserdejesus** [comment]
Ezee,  when I test Jamtaba in Mac 32 bits all things are working. But when I load a VST in Jamtaba the plugin editor is not opened and a error message appears in console. I don't remember the error message exactly but is related with "create an Carbon window (the plugin editor) and put this window inside a Cocoa window (the Jamtaba host window)".  

I read something about compile Qt to use Carbon, this is possible and perhaps solve the problem, because when create a Qt window we are creating a Carbon Window, and no conflict between Carbon (old Macs) and Cocoa (modern Macs). All this work is necessary to support Mac OSX 10.6, a lot of work, a lot of changes. So I take the easy path: Jamtaba run in Mac OSX 10.7+ (64 bits and Cocoa). 

If some Mac dev join in the team we can work in a better solution, but for while I think we can't support Mac OSX [32 bits using Carbon].

**Comment by Ezeer** [comment]
Okay ... so we have our minimum requirements for MAc , yeah ?
Mac OSX 10.7+ (64 bits and Cocoa). 
I put that on the FAQ , correct it if needed
--------------------------------------------
En date de : Lun 26.10.15, Elieser Ademir de Jesus <notifications@github.com> a écrit :

 Objet: Re: [JamTaba] MAC OSX 32 bits version (#41)
 À: "elieserdejesus/JamTaba" <JamTaba@noreply.github.com>
 Cc: "Ezee" <h2oreggae@yahoo.fr>
 Date: Lundi 26 octobre 2015, 13h30
 
 Ezee,  when I test Jamtaba in Mac
 32 bits all things are working. But when I load a VST in
 Jamtaba the plugin editor is not opened and a error message
 appears in console. I don't remember the error message
 exactly but is related with "create an Carbon window
 (the plugin editor) and put this window inside a Cocoa
 window (the Jamtaba host window)".  
 
 I read something about compile Qt to use Carbon, this is
 possible and perhaps solve the problem, because when create
 a Qt window we are creating a Carbon Window, and no conflict
 between Carbon (old Macs) and Cocoa (modern Macs). All this
 work is necessary to support Mac OSX 10.6, a lot of work, a
 lot of changes. So I take the easy path: Jamtaba run in Mac
 OSX 10.7+ (64 bits and Cocoa). 
 
 If some Mac dev join in the team we can work in a better
 solution, but for while I think we can't support Mac OSX
 [32 bits using Carbon].
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by elieserdejesus** [comment]
Ezee, It's correct. I'm not a Mac expert, but I think Mac 10.7+ are all 64 bits and Cocoa, so is enough write just "Mac OSX 10.7+", mentions to Cocoa and 64 bits are implicit. But I'm not 100% shure about this.

**Comment by elieserdejesus** [comment]
closing by inactivity
