### ISSUE TITLE
Theme names not available for translation

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#438]
I was doing a test updating the translation files for the new features and I found out that the theme names are not showing up in QT linguist. Only the theme menu is available for translation. I wonder if this names are fixed in the code and thus, not modifiable.

**Comment by elieserdejesus** [comment]
@jonjamcam , the theme name is loaded from the resources file. If you change the name of "Black" folder in resources the thema name will be changed too. But is not possible translate these theme names directly because these are dynamically created strings. Only the static/manually typed strings can be translatable using the Qt **tr** macro.

**Comment by jonjamcam** [comment]
> is not possible translate these theme names directly

How about something similar to the solution used for the language menu:

![image](https://cloud.githubusercontent.com/assets/15310433/15865880/dacb4232-2cb2-11e6-88c1-81eb35a8b299.png)

In this case, @elieserdejesus could those names be translated?

**Comment by elieserdejesus** [comment]
@jonjamcam , at moment the themes list is dynamically builded (and because this theme names are not translatable). If we build the menu entries "manually (not dinamically)" it's easy use the Qt **tr** approach to have translatable theme names. The negative side effect is: new themes added in resources will not be "auto recognized" (will not appear in the theme menu), the new theme need be hardcoded as other menu theme entries. I think the hardcoded menu entries are not a big problem since new themes are rare.

**Comment by jonjamcam** [comment]
> The negative side effect is: new themes added in resources will not be "auto recognized" (will not appear in the theme menu), the new theme need be hardcoded as other menu theme entries. I think the hardcoded menu entries are not a big problem since new themes are rare.

I agree.

**Comment by elieserdejesus** [comment]
@jonjamcam , the theme names are translatable now. It's necessary run lupdate to see the words Black, Flat and Rounded in your TS files. You can translate the spanish file and run lrelease to test.

**Comment by jonjamcam** [comment]
Perfect!

![image](https://cloud.githubusercontent.com/assets/15310433/15993983/032feb88-30cd-11e6-8b42-501770b3601d.png)
