### ISSUE TITLE
"Save multitracks option" checked DOES NOT record if the two other check boxes are unchecked

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#459]
I think this is important, specially for new users (from https://github.com/elieserdejesus/JamTaba/issues/444#issuecomment-225701728).

![image](https://cloud.githubusercontent.com/assets/15310433/16022317/9607b2b8-318d-11e6-8145-25fa7c2e0b46.png)

In this case the result is no recording at all (**not** even an empty folder is created). I suggest there should be a link of the "root" checkbox ('save multitracks' option) with the 'clipsort' and 'RPP' checkboxes, so if none of this last ones is checked, then the root checkbox should be unchecked too:

![image](https://cloud.githubusercontent.com/assets/15310433/16172507/7a6ccb24-3561-11e6-9d97-f8f8194fcc32.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I think in this case is better (more clear to users) remove the "Save multi tracks" and keep just the other 2 checkboxes.

But I think the @pljones idea was save "audio clips only" when only the "Save multi tracks" checkbox is checked. This feature (audio clips only) can be usefull for non Reaper users. If this is the case we need the 3 checkboxes. Can you confirm @pljones ?

**Comment by pljones** [comment]
Originally the idea was indeed you got the audio files all the time.  But we took this out as it was deemed confusing and made it so that each save format created its own output files.

I'd suggest the quick option for now is:

* Checking the "Save multi-tracks" should enable the other two checkboxes. 
* Unchecking it should disable them.
* The text should be followed by "Select multi-track format(s)".
