### ISSUE TITLE
Latency compensation control for ninjamers (received audio only)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#522]
I noticed some ninjamers "appear" to play off metronome by a slight bit. I understand this is a problem with their hardware and not of their timing. Not everyone is using good quality soundcards for jamming and some drivers do not compensate for latency, specially if you use the old Ninjam client and no ASIO driver.

This problem can be easily corrected if we had a little fader or knob per user that adjusts the incoming audio some milliseconds (+-from 0 to 100 ms is my first guess).

**Comment by NakajimaYusuke** [comment]
Hi, I have felt similar problems in NINJAM session.
Several ninjamer performances always sound a bit delayed from the metronome.
I guess most of the reason of this problem is because they are playing with direct monitoring.

During the NINJAM session, direct monitoring brings monitoring without any latency.
This is the advantage compared to "input monitoring".
But on the other hand, direct monitoring brings latency between "monitor sound" and "actual transmitted sound".

Even if "Direct Monitoring Ninjamers" plays perfectly accurate to the metronome, 
the actual transmitted sound will always be delayed a bit according to the ASIO buffer size.

Although it departs from the purpose of this thread,
I have posted an idea for fix this direct monitoring latency in Cockos forum before.
http://forum.cockos.com/showthread.php?t=167838
My idea is to correct this latency **before** transmission.
"Ninjam client reads the ASIO latency and fix the transmission timing a little early based on the ASIO latency."

I think the idea suggested by pljones is most clever.
http://forum.cockos.com/showpost.php?p=1587720&postcount=7
However, if this is technically troublesome, the idea I mentioned in the forum (method using delay effect) could be substituted.

I think it is very important and reasonable to erase the "direct monitoring delay" for NINJAM system.
Because, If the direct monitoring delay can be eliminated, all of the delays of the NINJAM session can be erased for direct monitoring NINJAMers.
For extreme example, If the direct monitoring delay elimination method is implemented, and all of member uses direct monitoring, a perfectly delay-free session will be realized  from anywhere on the Earth.

It is absolutely not realized in real-time based session system like Virtual Stage, Jamkazam or e-jamming audio.
Because they have the unavoidable  delay due to transmission distance. 

Perhaps NINJAM is the only session system that can completely reduce the auditory delay to zero. 
This is the privilege of the NINJAM system.
I think "latency compensation for direct monitoring" will bring good results to many people.

Sorry to derail the thread. But the root problem is probably the same.

**Comment by jonjamcam** [comment]
> My idea is to correct this latency before transmission.

Hey @NakajimaYusuke . You raise an important point here. There's another issue https://github.com/elieserdejesus/JamTaba/issues/182#issuecomment-294362463 to address the "direct monitoring" implementation. I think your ideas are related to that issue (https://github.com/elieserdejesus/JamTaba/issues/182).

I posted this "latency compensation" issue to address problems related to other clients that are unable to fix this issue locally.

**Comment by Hitrate** [comment]
Perhaps we need to also educate the youth/elders to lower their buffer settings locally, as I have found several just use 384 or even 512 because they claim they can't hear the difference..well guess what......we can ;) 

I dunno how related this is, but if there is a way to make sure Jamtaba starts at the ultimate point in time, when hitting the sync/play head button..like, I'm not sure it will not be around late in some instances, so that you're actually a full round further behind than you ideally could/should be...if that makes sense..So if theres a way for Jamtaba to make sure you always start streaming, also when tempo changing and re-syncinc, that you start streaming at the ideal spot related to your connection, rather than for it to sync even if you're then behind so to speak...I have always thought in Ninjam it would always be one full measure behind, but I guess that's not always the case..

Also, sorry just brainstorming here: it would be cool if there was like an auto-transmit-disable thing, where if let's say (which happens a lot) someone logs in and doesn't play but is still streaming empty audio...if after a set time, or a constant measurer of some kind (could be a timer, could be a gate..) if there has been no audio coming through (other than background room/cable/amp noise) that channel's transmission is disabled...when he/she then starts actually playing, his/her transmission will start again...I dunno if it's already doing this with greyed out channels, but many times I see none-greyed out channels not streaming any music, but still I'll have to manually hit the disable button on each of them, but then I don't know if they start playing, when to un-mute them again... :) All this would save huge bandwith for all users in a larger session ;)

Cheers guys.

**Comment by jonjamcam** [comment]
Obsolete... closing
