### ISSUE TITLE
FR Remember installation details

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#55]
When I update from one version to the next, I really should not have to tell the installer where to put all the bits -- they're already installed, it should be able to find them (after all, the uninstaller can to get rid of them).

**Comment by Ezeer** [comment]
yeah , we need to work on that installer .
We have also a problem with it for the win32bit version .

Elieser , could you give me some details on how to work with the installer ?
I think it is a priority now ( i can work on the win32 bug and that issue at the same time  )

**Comment by elieserdejesus** [comment]
Ezee, the installer scripts are in [Repo folder]/Client/installer/windows

The files are:
Installer script 32 bits.iss
Installer script 64 bits.iss
Installer script common.iss

The first 2 script are just creating some #define used in "Installer script common.iss"

To edit and compile these scripts install [Inno Setup](http://www.jrsoftware.org/isdl.php).
Inno setup is enough to compile and edit, but [ISTool](http://sourceforge.net/projects/istool/) too, it's easy and more visual.

**Comment by Ezeer** [comment]
okay , i'll work on that today .
thx elieser .
^^

**Comment by Ezeer** [comment]
I see in the script : 
" #define Redistributable "vcredist_x86.exe"

It is a visualstudio thing , no ?
Now that we use Mingw , we can rip that ?

**Comment by elieserdejesus** [comment]
Ezee, I'm using msvc stuff here because I have no good time trying MingW 64 bits. Actually the problem is not mingW, the problem is Qt for MingW 64 bits. 

The vcredist_x86.exe is installed if user don't have it installed in your machine. This exe install the C/C++ run time DLLs in the user machine. 

Just to test and tweak the scripts you can download the [redistributables](http://www.microsoft.com/en-us/download/details.aspx?id=40784) and change the paths in script file.

**Comment by Ezeer** [comment]
ok.
I'm working for Win32 release first anyway .
Then i'll check that enhancement requested by peter .
thx

**Comment by Ezeer** [comment]
So peter , i think i've found the fix to that problem in the FAQ of innoSetup : 
"  **Can Setup use the value of a registry entry as the default directory name?**

Yes. Use a {reg:...} constant in DefaultDirName. For example:

[Setup]
DefaultDirName={reg:HKLM\Software\My Program,Path|{pf}\My Program}

See the "Constants" topic in the Inno Setup help file for more information on {reg:...} constants.  "

I'm working on that ...

**Comment by Ezeer** [comment]
wow ... it is a pain to learn how to configure all that sh*** !
^^
Elieser , i've found an option in ISTool to fix that issue : 
( i use the french version so the words may differ ...)
Go to Project->Installer options->compiler->Folder tab -> check previous directory .
I think you should take that task , as there is a high level risk that i break the install system because
of noobysm ...
^^

**Comment by pljones** [comment]
In case you're not doing it already, when updating the installer, have it check some how that the program isn't running and tell the user to close it or quit trying to install.

(I've only used NSIS so can't offer any direct help on InnoSetup.)

**Comment by Ezeer** [comment]
**(I've only used NSIS so can't offer any direct help on InnoSetup.)**

Well , there is a place for someone dedicated in the install process ...
eh eh

**Comment by elieserdejesus** [comment]
I will work on this to the next release.

**Comment by elieserdejesus** [comment]
Done, installer remembering now!

**Comment by Ezeer** [comment]
Woo Wooo , thank you boss !
![boss-day-thank-you-messages-3](https://cloud.githubusercontent.com/assets/1283808/10766938/225cc05a-7cda-11e5-834e-c61ea91b9396.jpg)

**Comment by elieserdejesus** [comment]
hehe :) Please don't make me put my "Rambo" picture again :)

**Comment by Ezeer** [comment]
i know , it's closed .
But i don't remember the rambo thing ...
mmm....
.......
ah .... yeah ....
this one ?
![rambo](https://cloud.githubusercontent.com/assets/1283808/10767524/d036bf6c-7cdc-11e5-8c29-e3fd8c0d3cf2.jpg)

mwah ah aha ah adlib ....
