### ISSUE TITLE
why borders?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#581]
The new map allows instant visual location of musicians all over the world, so I did some tests erasing country borders and flags:

![image](https://cloud.githubusercontent.com/assets/15310433/18409754/44bde218-7726-11e6-83fd-b58e6f7f03dd.png)

I kind of like how the world looks this way, so I thought about suggesting the idea to you @elieserdejesus for future releases.

**Comment by elieserdejesus** [comment]
@jonjamcam , I like this **clean** visual without the country and flag infos. But sometimes we see some guy playing from a very "uncommon" country and without the name of this country I can't say **where** this person live/play. So, in these situations ("uncommon" countries) I think is cool see the country name. Another situation is when **all players** are from France or USA. In this case show the country name for every player is useless, since all country names are the same we are just bloating the user interface with repeated info. 

Maybe we can discuss some ideas to improve the map visual. I have 2 ideas to start the discussion:
1 - clean is good, avoid repeated or unecessary infos in the screen.
2 - Sometimes we need the country names. How we can show these names without bloat the screen?country names as tooltips on mouse hover? Another possibilites?

**Comment by jonjamcam** [comment]
> country names as tooltips on mouse hover?

I was thinking the same thing. Best of both worlds.

**Comment by elieserdejesus** [comment]
@jonjamcam , in your map picture the waveform is drawed in top of ninjamers names. I like this approach too when the visual elements are not overlapping (this is the case in your picture). But when the server is full we will see a lot of overlapping between ninjamers names and the waveform. The result is a bit confuse (I tested this approach when writing the MapWidget code). 

My first ideas to solve/minimize the overlapping problem was draw the waveform in top or bottom, not in center. But the result is not good too because sometimes the ninjamers names will be in top or bottom, causing overlappings.

Another idea is use more alpha/transparency in the waveform drawing.

**Comment by jonjamcam** [comment]
> use more alpha/transparency in the waveform

I like the more alpha approach.

But if that is not enough, here's another idea:

![](http://www.vancouverarchives.ca/wp-content/uploads/2013/01/optical_sound.jpg)

This is a film section with "optical sound" at the side in vertical form. It used to be this way in the early XX century. Maybe it could look good if it's small size.

 It's very nice to see how names appear and move when listening to the room, but your original solution was also very clean.
