### ISSUE TITLE
Creating 3rd channel to handle open264 low fps & image size for cam.

### ISSUE THREAD

**Issue by AndyMcProducer** [elieserdejesus/JamTaba#590]
Hi, would it be possible to add to L & R a C channel to encode and decode video using open264 codec.
FPS and image size would need to be low to accommodate similar bandwidths.
Would this not t hen be invisible to older clients but used by newer clients?
I ask as I'm not sure if the server would need to handle an extra channel, or be told to pass on data same as audio l & r.
From what I see their is no real time code associated with the audio, it is plucked, pushed and pulled, could this been done but the metronome per block be used as a reference to replaying frames?

**Comment by jonjamcam** [comment]
Good idea to stream video. I was thinking about another possible solution if the third channel is not compatible. Use the second ninjam channel as video only (if video is supported by the server)

**Comment by AndyMcProducer** [comment]
The server source would need updating. I think the best way to do video would be to allow rmtp: links, then peeps can either use an IP cam software which a few simple ones exist or use one of the many online streaming services. Even Facebook live provides the direct link.



Get Outlook for Android






On Tue, Sep 13, 2016 at 4:57 PM +0100, "jonjamcam" <notifications@github.com> wrote:





Good idea to stream video. I was thinking about another possible solution if the third channel is not compatible. Use the second ninjam channel as video only (if video is supported by the server)

**Comment by elieserdejesus** [comment]
> would it be possible to add to L & R a C channel

@AndyMcProducer , your idea is mix a third stream (the video) in the vorbis data? I understand correctly?

If yes, @jonjamcam mentioned multi audio channels in vorbis in another issue. I'm not sure if ninjam clients can handle more than 2 (L + R) audio channels per stream. If the clients can receive a 3 channel audio stream (L, R and video data) this will be interesting, because Jamtaba can detect the third channel and render the video data. Another clients will discard this extra data.

**Comment by jonjamcam** [comment]
Last Friday we had a nice camjam with obs studio. I'm really impressed by the quality of the image streamed on youtube. @AndyMcProducer knows the nuts and bolts of how it works, but I understand Tom set up a rtmp server or something. Have you seen this working @elieserdejesus?

If Jamtaba could stream the video just like OBS Studio does I'm sure we'll have lots more of cams switched on in the future.

**Comment by elieserdejesus** [comment]
@jonjamcam and @AndyMcProducer , I tested some ideas streaming "non ogg vorbis" data in ninjam. I have good results. If we send a "non ogg vorbis" data in ninjam channels the old clients (ReaNinjam, etc) will just drop these data, because the data is not "tagged" as ogg vorbis. The servers are not filtering these packets too. So is possible send "uncommon" data without crash servers or old clients.

I tested sending a "uncommon" byte sequence *(simulating a not ninjam compatible video stream)* and got the same bytes sequence in the other side. The conclusion is: we can send/receive anything in ninjam streams and JamTaba can recognize specials "tags" in these streams end render the video. A video + audio channel is possible too.

Tom (from ninbot) ask me about work togheter in a video solution using rmtp.

My first idea is just stream the video data directly to ninjam server (a common server, not a rmtp capable) and these streams will be "broadcasted" to connected (in same server) players, exactly as ogg vorbis are broadcasted at moment. Old ninjam clients will receive the video data and ignore/drop *(I tested this hypothesys and works)*. JamTaba will see the special video flag in the stream and can render a small video retangle in the ninjamer channel strip (or another solution).

Using this first (and simple) idea we don't need external software to stream video, and a rmtp server is not needed too. It's not clear in my mind if we really need a rmtp solution. 

Maybe a possible solution is the ninjam server grab all video streams and mix in a final video stream like bandhub [https://www.youtube.com/watch?time_continue=57&v=SVo6fIdu4_Y](https://www.youtube.com/watch?time_continue=57&v=SVo6fIdu4_Y). 

This "final video" can be available as a rmtp stream and rendered in ninbot home page, rendered in JamTaba "world map" window, etc. Any rmtp capable software can grab the link and render the "final mixed" stream.

**Comment by jonjamcam** [comment]
>It's not clear in my mind if we really need a rmtp solution.

Hard choice. So the alternatives I understand with regards to video are basically:

1.- Jamtaba uses it's own video solution "muxing" the audio and video.
2.- Jamtaba joins some kind of standardization effort using rmtp via ninbot.

I think at this point we have some critical mass for the second solution. It's already happening; the infrastructure and bandwidth is there for all clients and I've seen it work pretty much flawlessly (session with more than 8 cams working perfect!). Hats off to Andy and Tom for the results. I know both have been trying something that works for years and now it's happening.

Having said that I think for the long term the first solution is the best one, simply because it opens lots of other possibilities (like multitrack streaming, surround sound, etc.). But this approach could be a problem for small servers (like mutantlab) if bandwidth requirements are too high.

So there's the technical aspect, but very important too is the "social" part of this equation. Ninbot.com has been pretty much the backbone that has kept all of us together for years because of the forums, the recordings, of course the bandwidth, but most importantly the idea of a community. 

 Personally what I like about Jamtaba and your personal vision @elieserdejesus is that you've built something that is not "apart", but "a part" of the same effort. This is important for me and is the energy that keeps me glued to the project.

 So I think (if it's technically possible because of compatibility) this should be a converging process. I think it's a good idea for Jamtaba to implement the rmtp solution to start with (of course if it's not a pain to code), so the video solution is "a part" of the same effort Andy and Tom started. Then, maybe over time the other alternative will come as an "enhancement" and people can choose which they will use the same way today you can choose to connect to ninbot or ninjamer or localhost.

I hope this long post make sense :roll_eyes: !

**Comment by elieserdejesus** [comment]
@jonjamcam , I undestand your point about being "a part". I think this is very important too. 

From a tech point of view is more simple for me programming without the rmtp stuff, just because I'm totally zero in rmtp field. But I'm planning use the FFmpeg library, and this lib can handle a lot of audio and video codecs and rmtp stuff (I hope).

**Comment by jonjamcam** [comment]
> From a tech point of view is more simple for me programming without the rmtp stuff

I should say that's very easy for me to stand on a rock and preach all kind of virtues about this and that when I have absolutely no idea how to code it!

Just a funny thought :smile:

**Comment by AndyMcProducer** [comment]
Hiya, i meant using 3rd channel as the audio for voice.
But the idea of pulling video via a rtmp link means server hosts the bandwidth.
If you push the video then 1 person would need to restream to every person. 
Using an rtmp link, this could be integrated into ninbot site/server or someone can simply choose live on one of the many free services and enter in the rtmp link.
All jamtaba needs to do then is pull the lowest resolution stream.
Audio could either be live from that or via a no delay 3rd hidden Ninjam channel. Although it makes more sense to use the audio in the video stream.
Start there then progress itv as we start to get an idea of what needs adapting.
Although if you do it as a channel on Ninjam then allow for it to be turned off or max cam settings or audio only. For people with less bandwidth. If Ninjam server handled the data then this would increase the server's data usage so this needs considering when creating.

**Comment by AndyMcProducer** [comment]
A lot of streaming apps, like YouTubes, Facebook, twitters periscope etc give you the rtmp link. A lot are now aiming for people to go live in the moment so latency of those services is very low now,

**Comment by AndyMcProducer** [comment]
The way you have worked it Elieser is who I was first thinking but i worry even though the data is dropped that it is still received in the first place. Being able to utilise though a data type channel in ninjam is great.
I think this channel could be what jamtaba can use to do its extra stuff, this way data can be kept to a minimum. Video in this way would be synced but would be delayed also by BPI.
Unless it was sent as soon as it was encoded, then there would be only a small overhead of latency for encoding, sending, receiving then decoding. It would be worth coding a test to simulate 7 channels of audio and video, checking server bandwidth, CPU usage. Or get 7 of us to beta test it at once. If issues which can't be overcome are found early then it saves you time in the long run. Also it can be other than rtmp, the ningx server Tom runs can do other types too.

**Comment by AndyMcProducer** [comment]
This may help a lot for alternatives, including some p2p options. https://en.m.wikipedia.org/wiki/Comparison_of_streaming_media_systems

**Comment by AndyMcProducer** [comment]
You've also got HLS http streaming which may be better for adapting to changing bandwidth.
https://en.m.wikipedia.org/wiki/HTTP_Live_Streaming

**Comment by jonjamcam** [comment]
@elieserdejesus I did some tests with the formats that youtube uses and I'm concerned about the amount of bandwidth used. I hope the FFmpeg library you are using has better performance ratio than youtube.

 The problem as I see it here is that Jamtaba will use any channel for video which need to share bandwidth with the audio, right? And because Jamtaba is limiting the bandwidth to 128 kbit/s per channel, both audio and video must not use more than this limit when transmitted.

 I suppose this means that to any channel the alternatives are:

1.- audio only (as now)
2.- video only
3.- audio and video

My tests show that the minimum quality that youtube offers (and it's very low) is 144p and it consumes in real terms about 76 kbit/s of bandwidth (9.5 kb/sec). I tested 240p that is much better and it gave me about 221 kbit/s (27.6 kb/s). This last value is completely out of the question if we have a hard limit of 128kbit per channel. (one caviat here, youtube transmits audio and video, I suppose only video should have better quality for the same bandwidth)

To put this in context, we did measure the audio bandwidth of the ogg encoder before (here https://github.com/elieserdejesus/JamTaba/pull/462):

QUALITY_LOW = -0.1f; // ~48 – ~64 kbps
QUALITY_NORMAL = 0; // ~64 – ~80 kbps.
QUALITY_HIGH = 0.3f; // ~112 – ~128 kbps.

So 76 kbit/s of video will leave about 52kbit/s of audio which is less than the lowest quality available today and even lower (or at best the same) to what reaninjam offers.

So my conclusion is that the video channel should be video only for two reasons:

1.- I suppose 128 kbit for only video can have acceptable results.
2.- If one channel has audio and video muxed then there is the problem that other clients may discard the whole channel, not only the video.

**Comment by elieserdejesus** [comment]
@jonjamcam 
>  Jamtaba is limiting the bandwidth to 128 kbit/s per channel

This true for **ogg vorbis encoder** only, to encode video I will use a different encoder and we can use any bitrate/quality for video, it's not limited to 128 Kbps. As you know we need work with low quality video to avoid "burn" the ninjamers bandwith.

> 2.- If one channel has audio and video muxed then there is the problem that other clients may discard the whole channel, not only the video.

This is true. Mix audio + video is the best solution to keep audio and video in sync, but old clients will discard all received data.

**Comment by AndyMcProducer** [comment]
It would be cool Elieser to allow a image for when cam is not on. With a little mic and camera button on our cam to enable, disable cam or audio.

**Comment by elieserdejesus** [comment]
shure @AndyMcProducer , I will finish the v2.0.20 in next days and start the video in next weeks.

**Comment by jonjamcam** [comment]
Some ideas before I forget:

 I propose to set a hard limit of overall bandwidth upstream per channel for BOTH AUDIO and VIDEO of 128 kbit and try to maximize it's use. It is my opinion that Jamtaba should allow only low quality video for this method (video track streamed to ninjam server) at least in the first stages of the implementation.

To allow high quality video there's already the rmtp solution using obs studio and this is good because ninbot.com is already prepared for this kind of usage. This is not the case for ninjamer.com and mutantlab.com . I fear the huge demand of bandwidth that high quality video has could be considered abuse by it's owners.

 I'm completely sure that as soon as people realize video is supported, everyone will start using it and setting the highest quality available. This is great for the community because we'll be able to see many more people, but it can really harm the little public server infrastructure we have today. 

So assuming we have max 2 channels per client and each channel can have **video only** or **audio only**, we ca set the VIDEO QUALITY to the same standard than the audio:

VIDEO QUALITY_LOW -------> max ~64 kbps
VIDEO QUALITY_NORMAL  -> max ~80 kbps.
VIDEO QUALITY_HIGH ------> max ~128 kbps.

This way there will be no change to the requirements on the public servers at all!

**Comment by jonjamcam** [comment]
> Maybe a possible solution is the ninjam server grab all video streams and mix in a final video stream like bandhub https://www.youtube.com/watch?time_continue=57&v=SVo6fIdu4_Y.

>This "final video" can be available as a rmtp stream and rendered in ninbot home page, rendered in JamTaba "world map" window, etc. Any rmtp capable software can grab the link and render the "final mixed" stream.

I was reading again your previous post @elieserdejesus and I missed this part completely. I think it's a great idea that you can have a "video mix" per server in the ninbot page just like you have and audio mix. And you could see this video mix directly in Jamtaba too? nice! You mean when you press "listen" you'll be able to watch the video too instead of a map? 

![image](https://cloud.githubusercontent.com/assets/15310433/25414173/583d559c-2a06-11e7-9f83-de61909e51b6.png)

This idea combined with obs studio for other clients that do not support video covers the whole visual needs of everyone I think.

**Comment by elieserdejesus** [comment]
Exactly @jonjamcam , this is my first idea. In this idea JamTaba will do 2 things:
1 - capture the camera frames, encode and send to ninjam server as a "video interval".
2 - ask public servers about a video stream rmtp link and render this "mixed" videos, exactly like the servers audio preview link.

This idea need some work at server side because is necessary program servers to mix the videos and generate only one video stream.

**Comment by AndyMcProducer** [comment]
Elieser if the server is going to encode then consider openCL to allow the GPU to handle the encoding.

**Comment by AndyMcProducer** [comment]
Also Eli, you know obs can host a VST now, so could run Jamtaba within it. I don't know if this will help in getting video direct into obs but it might be worth looking into it. If the server was a VST which I know would probs be a prob but it could show cams in it's gui as a vst meaning they would be their to stream in obs. If the background was set to transparent then they could be very easily mixed in obs. Or a simple cut down version of jamtaba that was maybe called TabaCam or similar, which just loaded as a vst and showed and pulled just the cam feeds from the server.
It would save needing the host server to compute video encoding too. Like ninbot and ncast bot they could simply sit in a server and grab info. Also with a bot new cool things could be done with out too much needing or any need to use new server code.

**Comment by AndyMcProducer** [comment]
TabaCam could pull audio from server too with a bit better ability to mix audio.
This could even be a way people could run a ninjam server to do video conferencing too, later you could add integration to social stuff.
One of the sites I stream too, i think it's connect cast have a edited version of obs just for their site.
It's cool everything being in one program but at the same time people love to sorta build their own thign from many things. I think you could save yourself tons of hassle, have more fun with it whilst still allowing many possibilities by just having a few programs than just one.

To make TabaCam or similar it would be a lot simpler than trying to integrate into the server code, which would mean only those who use the new server compile would support the new options.
Where as if you managed to push data through the orig server with out the need to modify it then this makes all servers compatible, then a simpler version of jamtaba vst to sit in obs which just pulls cams and maybe audio. Could end up being Jamtaba MixDesk VST which could later become a non ninjam way to pull in cams too, like say fb, youtube, hangouts and other rtmp streams and mix them together.
There isn't a simple solution anywhere for that atm, only pricey pay software that doesn't simply allow someone to pull a load of sources.
OBS can do this but having a vst that can make it simple and auto arrange cams on screen just doesn't exist and so many would like to be able too.

**Comment by elieserdejesus** [comment]
@AndyMcProducer 

> obs can host a VST now, so could run Jamtaba within it.

I see this option in OBS, but I think this will be confuse for non-tech users. The JamTaba idea is always "the most simple setup for end users, and ZERO setup if possible". I understand this is not too interesting for advanced users, but I think we need tools "for dummies". I can resume the JamTaba general idea as: "Just play, don't think!" he he he :)  To configure/setup OBS people need think about rmtp servers, IP, ports, video resolution, etc. and this is not enough "user friendly". Many people just will say: "not for me, too complicated, I'm just want to play some music!". 

***

> a simple cut down version of jamtaba that was maybe called TabaCam or similar

TabaCam is a good name :), but I have no free time to develop and delivery another software. So TabaCam is not for me, but I will be happy if another person assume this idea.

***

> only those who use the new server compile would support the new options.

This is true.  A possibility is release a bot (like the audio bots) to keep connected in servers capturing ninjamers video streams and encoding a "muxed" video.

My first idea is just capture the local video and send to ninjam server. This video will be broadcasted to connected ninjamers. This is the most simple approach I can imagine. After this I think will be more simple change the approach to something more flexible like "stream to an external rmtp server". I will start with the most simple approach to avoid blow my mind :)

**Comment by elieserdejesus** [comment]
Hi guys, just reporting some progress in the "video" feature:

**Camera preview** (very "raw", no buttons to turn cam off, just the basic stuff at moment) 
![image](https://user-images.githubusercontent.com/1012741/27287462-1c1d98b6-54da-11e7-8963-fd8ac1f029d1.png)

***

**Encoding/decoding mpeg4 using the FFMpeg lib**:
![image](https://user-images.githubusercontent.com/1012741/27287605-9e5912c4-54da-11e7-8e4e-2d0c7f946edc.png)

***
The next steps are:
1 - send the encoded video data to ninjam server, 
2 - receive the encoded video data, decode and render in ninjamer track.

**Comment by jonjamcam** [comment]
yeah! amazing! @elieserdejesus

**Comment by AndyMcProducer** [comment]
Eli to save room and clutter why not have words at bottom, click to turn off , right click for settings s or settings up in menu.  So when no cam showing a icon of video cam or webcam.

**Comment by elieserdejesus** [comment]
> to save room and clutter why not have words at bottom

@AndyMcProducer , are you talking about the user name and "Your controls" label?

> click to turn off , right click for settings s or settings up in menu. So when no cam showing a icon of video cam or webcam.

Exactly @AndyMcProducer , these are my ideas too. At moment is just a very initial experiment with video transmission.

**Comment by elieserdejesus** [comment]
**Just reporting some progress with video stuff**:  at moment is possible transmit and receive video streams (the UI is ugly and not polished yet):

![image](https://user-images.githubusercontent.com/1012741/29996794-bc9a59be-8fdb-11e7-85d8-537cce1472fa.png)

**Comment by jonjamcam** [comment]
Cool!

**Comment by elieserdejesus** [comment]
implemented in https://github.com/elieserdejesus/JamTaba/commit/4cc6f430b7e6a62515e78ff19e8afc637cb12168

**Comment by AndyMcProducer** [comment]
I've got the Beta with video, although I gotta check with you, is it using flash or something else, as I need to change camera selection and I imagine atm it picks up first in list or cam set somewhere else?

**Comment by elieserdejesus** [comment]
Andy, JamTaba is using **FFmpeg** (the library, not the executable) to encode the video streams. The camera is setted to the low resolution available and the video FPS is fixed (at moment) in 10 frames.

At moment JamTAba is picking the first available camera, I will implement the camera selection before release the official version.
