### ISSUE TITLE
[IDEA] Add "xN" notation to ChordLanguage(TM) :-D

### ISSUE THREAD

**Issue by vector21** [elieserdejesus/JamTaba#601]
With "xN" I mean a statement like: x2, x3, x4 ... etc

If we could add this to the "chord language" then a statement like 

!Gm7x4 !Bm7 !Am7 !Gm7x2

would result in such a chord pattern:

| Gm7                        | Bm7 | Am7 | Gm7         |

(4 times Gm7, Bm7, Am7, 2 times Gm7 --> filling up a 32 bpi interval)

What do you think?

instead of "x" a "*" would also work! ;-)

Have a nice day,
Ech

**Comment by elieserdejesus** [comment]
@vector21 , this is a good idea. But you wroted
> a statement like !Gm7x4 !Bm7 !Am7 !Gm7x2 would result in such a chord pattern: | Gm7 | Bm7 | Am7 | Gm7 |, (4 times Gm7, Bm7, Am7, 2 times Gm7 --> filling up a 32 bpi interval)

Is this pattern correct? I think the correct is
```
| Gm7 | Gm7 | Gm7 | Gm7 | Bm7 | Am7 | Gm7 | Gm7 |
```

**Comment by vector21** [comment]
Hello Eli,

Hmmm... yes basically you are right... It would result in the above chord bar.
But would it be possible to have it look like this:

![chordbar](https://cloud.githubusercontent.com/assets/5586556/18623512/5d9a0a40-7e3e-11e6-98e3-a02c13e782f1.png)

That would make it much more cleaner and easier to read. Also a notation like this would make sense:

| Gm7 % % % | Bm7 | Am7 | Gm7 % |      (where every % repeats the last used chord once)

Good day to you all!
Echna

**Comment by elieserdejesus** [comment]
Echna, now I got it. I think this is possible, a bit more complex in the implementation, but is a very interesting idea.

**Comment by elieserdejesus** [comment]
@vector21 , I tried this idea some days ago. Honestly, the result is not good. I realized type chords in chat is not a good solution. We need a good graphical chords tool, not a "chat chords tool". Type chords in the chat is very primitive in my opinion. We are used with chords in chat because ninjam clients are limited in this topic, but we can think in better tools. I will put a "Graphic chord tool" in the tasks list (#801), please feel free to contribute.
