### ISSUE TITLE
browser channel

### ISSUE THREAD

**Issue by qulf** [elieserdejesus/JamTaba#715]
some idea to add "browser channel" to play sounds from chrome, firefox  or other external sources.

**Comment by elieserdejesus** [comment]
@qulf , I think using ASIO (Windows) this is not possible, because when a host is using the ASIO driver no other software can use the same audio device. 

For example, when I'm using ASIO4ALL and start JamTaba or Reaper the audio system can't be used in browsers or any other audio software. 

I can't imagine (at moment) a WINDOWS + ASIO way to grab external audio. I think this is possible in LInux (Jack) and Mac. Maybe [Jack for windows](http://jackaudio.org/faq/jack_on_windows.html) is the best solution for your needs.

**Comment by qulf** [comment]
But if we using two audio devices. Most of us using some audio interface and wy still have onboard audio.  Mayby we can use them for broswer? . I will try that jack for windows

**Comment by elieserdejesus** [comment]
Using 2 devices is possible, but I'm not shure. I never tried use 2 ASIO devices at same time, I think some kind of sync is necessary to keep the 2 devices speaking "same language".

**Comment by jonjamcam** [comment]
@qulf have que tried using a phisical audio cable to connect the output of the onoard sound card (browser) to the input of the audio interface?

**Comment by qulf** [comment]
Yes that works but my gear is limited and I can get just mono with some noises

**Comment by elieserdejesus** [comment]
@qulf , maybe another solution? [http://vb-audio.pagesperso-orange.fr/Voicemeeter/](http://vb-audio.pagesperso-orange.fr/Voicemeeter/)

**Comment by qulf** [comment]
Thanks elieserdejesus I will try later. :).

**Comment by qulf** [comment]
yes voicemeeter works but on my system i need make bigger audiobufer in asio drives and my latency is also biger. voicemeeter looks like great software but is too big and too many options. not for me, not for my gear

**Comment by elieserdejesus** [comment]
@qulf , I'm closing the issue since I can't imagine how solve this insice JamTaba. To solve this you need some external tool (hardware or software).
