### ISSUE TITLE
vst jamtaba  trouble  on chat 

### ISSUE THREAD

**Issue by squiergtr** [elieserdejesus/JamTaba#731]
hi to all there isa trouble on the vst jamtaba  version 2.0.16 on ableton version 8  i can,t type in the chat 
i can receive on the chat have seen this same trouble on a early version before ..thank,s for your time on this issue ..

**Comment by jonjamcam** [comment]
hey @squiergtr Please update to Jamtaba 2.0.19 to solve chat issues.

**Comment by squiergtr** [comment]
hi elieser how do i contribute with a donation to the project and i just
download 2.0.19 will give it a go..

**Comment by elieserdejesus** [comment]
Hi @squiergtr , I aprecciate your intention to donate, but at moment is not necessary. Please help us testing the software, this will be a great help because we  can't test all situations, including all hardware + Operation System + DAW possible combinations. We need the help of users to know if JamTAba is working fine or not in the end user machines. And you can contribute sharing your ideas about **how to improve?  how the jam experience can be better?**. 

**IF** in future the JamTaba server generate more costs we can add a donate button in the website or in JamTaba, but this is not necessary at moment. 

This month the server costs reached the most high value in JamTaba history: 18 US dollar cents. The last high bill I remember was 4 cents, and in many of months the cost is zero because the usage not reach the GAE](https://appengine.google.com/) minimum billable values.

Again, I aprecciate your intention, but money is not a problem at moment! Thank you and please keep using JamTaba, reporting the fails and sharing ideas about how to improve!

**Comment by squiergtr** [comment]
hi elieser thanks for the fast reply i will give it a good test on ableton
ver 8 i dont like ver 9 as of yet .lol
i use jamtaba and  ableton on my  old dell core 2 with 2gig and it runs
very smooth no crash on the ver 2.016
i have the new ver 2.0.18 install as of now i seen ver 2.0.19  64bit did
not a 32 bit my os win7 is the 32 bit
i keep a look out when you have the 32 bit to download..ps i seen on
ver2.0.18 vst.. i could not resize the windows gui
at all it stay,s in mini size a nice feture would be the vst gui to adjust
to fit on the laptop screen ableton on the left and jamtaba on the right
this help us ableton user,s  a horizontal and vertical adjuster. this will
help on the visual side of operation.
and thanks on the reply on donate i am glad to help on the detonation when
needed..so setup the donation button
all the musician on ninjam are rich $$..lol
godbless and thank,s so much for your time ...peaceout

**Comment by elieserdejesus** [comment]
> i keep a look out when you have the 32 bit to download..ps 

@squiergtr , please check the **Downloads** section, JamTaba is available in 32 and 64 bits.

> i seen on ver2.0.18 vst.. i could not resize the windows gui. at all it stay,s in mini size a nice feture would be the vst gui to adjust to fit on the laptop screen 

This is improved in v 2.0.19, no more "mini size", you can increase and decrease the plugin window size.

**Comment by squiergtr** [comment]
hi elieser i am very sorry for being the idoit of the day i check the vst
menu on the current version and it is the 2.0.19
installed not the 2.0.18 as i thought soooo i still have the gui window
trouble it come up in ableton with the mini widow and can,t increase or
decrease in size should i post the trouble on the issue forum.. everything
else is working vst on ableton..

**Comment by elieserdejesus** [comment]
@squiergtr 
> can,t increase or decrease in size

This will occur if your window is small (laptop). If is not the case (your window is big) we have a bug.

**Comment by squiergtr** [comment]
hi elieser  with the early version i was able to go from mini to full
screen with this version 2.019 it,s stay at the  mini size
no worry,s i happy i can jam an chat  with the mini size  maybe it can be
work on the next version
my screen size is 16inch hz and 12inch vrt a standard dell  laptop latitude
...what should i do next
should i report the bug..

**Comment by jonjamcam** [comment]
@squiergtr You can setup a custom size for the VST plugin manually. This is explained in the manual:

![image](https://cloud.githubusercontent.com/assets/15310433/23594862/27a563ca-01fc-11e7-8030-a90c2532b1a6.png)

What you can do first is try increasing high and/or width adding 10 or 20 pixels (do this with Jamtaba is not running). Then restart your host and see. Repeat until you get the perfect size. I did this in my laptop. I got a perfect 655 x 1350 size:

![image](https://cloud.githubusercontent.com/assets/15310433/23594956/de78649e-01fc-11e7-9804-89d7732a2e27.png)

I use Reaper as Host and it looks like this:

![image](https://cloud.githubusercontent.com/assets/15310433/23594978/0b58cde6-01fd-11e7-9d46-af493388cdce.png)

I hope this can help you.

**Comment by squiergtr** [comment]
thanks elieser ill give it a go thank,s so much godbless
