### ISSUE TITLE
[VST Plugin - Looper] Looper windows do not stay on top if JamtabaVST's GUI is closed and restored again

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#783]
The Looper windows stay in the back and you can only see on top one at a time:

![image](https://cloud.githubusercontent.com/assets/15310433/24455229/23798fc6-1465-11e7-82f5-d1e5c102a4e7.png)

You can even minimize reaper and the looper windows stay in the background:

![image](https://cloud.githubusercontent.com/assets/15310433/24455164/f2ccb808-1464-11e7-8763-e9c2d9289cc8.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , tested and confirm the issue here. 

In my test I opened the looper window and close Jamtaba VST window. The looper window stay opened. I think make more sense close the looper window when the main window is closed. The looper window is a "subwindow", if the plugin main window is closed we can assume users will work in another inserted plugin, for example, and is better "auto close" subwindows. 

what do you think?

**Comment by jonjamcam** [comment]
>  I think make more sense close the looper window when the main window is closed. The looper window is a "subwindow", if the plugin main window is closed we can assume users will work in another inserted plugin, for example, and is better "auto close" subwindows.

Yes. I agree 100%
