### ISSUE TITLE
AU plugin issues

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#806]
@Hitrate reported some AU plugin issues:

- [x] Can't sync in Mainstage. It brings me the popup saying to set mainstage to bpm XXX unlike in logic where it then once the tempo is set says press start to sync.

- [ ] Also on the sync issues: in lpx when the bpm changes while in a room, when I change the bpm in lpx and then sync up, my sequencer is now not starting at 1. I believe it might also have to do with things on my end (perhaps a setting I need to change) but it would be nice if somehow it could make sure to start back from 1 automatically..

- [ ] in mainstage jamtaba is using 100% CPU

**Comment by Hitrate** [comment]
Upon further testing, it's actually more stable than I thought, and the tempo sync is working...you have to be a bit strategic about it in terms of when to hit play, and sometimes spend a few tries for it to match up with my external midi sequencer and the playhead in logic - where it matches with the bpi and everything.. (though still no sync luck in Mainstage, I'm a Mainstage noob though).

Other small things: Would it be possible for the peakmeter to drop after a while, or ad an aditional dot that falls off, cause you might have been at -2 at one point, but now you're at -24 but you have to manually click to make it drop and re-check your peak levels..if that makes sense..

Also, it would be cool to have expandable ui OR for there to be room to see all players on the screen without having to scroll up and down (when in traditional ReaNinjam horizontal view) ((well actually it's also a problem in vertical view if there are many players in the room)).

Lastly, one thing I'm getting randomly is dropouts where I only get sound out of one channel...left or right, can't remember..Anyway, if I go to settings in logic and switch soundcards and reapply my external soundcard, it'll fix it..sometimes I'll have to remove Jamtaba and reinsert it....I'm using Focusrite Saffire Pro 24 DSP directly via firewire to a healthy MBP '11 15" i7 2.2 with 8 gigs of ram and a 500 gig SSD on Mavericks 10.9.5 with latest Logic.

All the best

**Comment by elieserdejesus** [comment]
Hi @Hitrate 

>Also on the sync issues: in lpx when the bpm changes while in a room, when I change the bpm in lpx and then sync up, my sequencer is now not starting at 1. I believe it might also have to do with things on my end (perhaps a setting I need to change) but it would be nice if somehow it could make sure to start back from 1 automatically.. 

I don´t know if possible for AU plugins change host play head. I´m shure this is not possible in VST, so I suppose is not possible in AU too.

***

> though still no sync luck in Mainstage

I fixed the code and is working fine in MainStage 3. The sync bug is very difficult to test, if this bug appear again please try help me to identify how reproduce this bug.

***

> Would it be possible for the peakmeter to drop after a while

Actually this peak meter is being dropped in the last version. Now a audio meter with dB markers is used.

***

> it would be cool to have expandable ui OR for there to be room to see all players on the screen without having to scroll up and down

In big screens is possible *increase/decrease* the AU plugin size in the **View** menu. Another 2 tricks are: 1) collapse the local tracks (in left side) to get more horizontal space; 2) Inside a ninjam server you have 2 buttons to switch between narrow/wide tracks. Narrow tracks will allow more users in the screen without scrolling.

**Comment by Hitrate** [comment]
Hey Elieser. Yes, great ! 

About the playhead thing, obviously I'm not experiencing this problem now in mainstage, as there is no playhead lol...but regardless, it was not a vst nor an au creating the problem..what happened/happens is if you're not correct on the timing of you pressing the play head and thus syncing up, or if you where synced, someone changed the tempo - then when re-syncing LPX it would not start my sequencer on beat 1 on the sequencer..which was kinder bothering me as it gives bright visual feedback on the illuminated 16 pads :) On this topic though, it is also kind of frustrating to receive the "BPM has changed" popup, cause it's quite obtrusive and forces you to click and make the daw tempo changes, do the syncing again, re-sync if it didn't sync to the sequencer etc...This is not taking au into account, just the actual DAW and the way it works together or not with jamtaba :)

Also, as you see in the screenshots, it looks like Jamtaba is using an excessive amount of system processes/cpu..might have been "fixed" a bit since it's now not always on 100% but still...And also in screenshots you can see how there's no room for all players regardless of settings....also I can't increase/decrease the size, not sure how you would do that there's no arrow to narrow or widen it etc. and it's not like in native logic plugins where you can set it to 150% lets say..

Thanks for you efforts, all in all Jamtaba rocks even with the minor kinks and challenges ! 👍 

![screen shot 2017-04-22 at 07 18 15 am](https://cloud.githubusercontent.com/assets/26333462/25315595/e07ac986-2857-11e7-9893-89529712a174.png)
![screen shot 2017-04-22 at 07 18 26 am](https://cloud.githubusercontent.com/assets/26333462/25315593/e0732488-2857-11e7-87df-8a58daf4de62.png)
![screen shot 2017-04-23 at 07 03 58 pm](https://cloud.githubusercontent.com/assets/26333462/25315594/e07729ca-2857-11e7-8b89-393d5580c384.png)
![screen shot 2017-04-23 at 07 04 43 pm](https://cloud.githubusercontent.com/assets/26333462/25315592/e072fbca-2857-11e7-99b1-db117a91a342.png)

**Comment by Hitrate** [comment]
Basically I like not having to use my mouse too much, so scrolling in the chat to see the 6th previous message, scrolling through the players etc. takes away some of the focus on playing..

As you see in the screenshot below, there really is a lot of "wasted space" especially in the chat, meaning you have to constantly scroll up/keep your eyes on the screen, to read it in time..Maybe widen/option to increase/decrease size of chat room, or just make each persons blob not take as much vertical space, so there's more room for text and to read what was written 5 mins ago..with this many plugins these days, every pixel on the screen counts :P

![screen shot 2017-04-23 at 07 30 29 pm](https://cloud.githubusercontent.com/assets/26333462/25315798/638b057c-285b-11e7-84b3-87ca6ad287d3.png)

**Comment by elieserdejesus** [comment]
@Hitrate 
> looks like Jamtaba is using an excessive amount of system processes/cpu..

I tested in MainStage 3, and after fine tune all optimizations my CPU is about 80%. 

Tested in Logic Pro 9 and the result is much better (~32%). I tested the same server (3 musicians playgin) and I was xmiting 2 channels (ogg vorbis encoders are using a lot of CPU). My conclusion is: **MainStage is a complicated guy, and Logic is a nice person** 😄 

![screen shot 2017-04-24 at 11 24 50 am](https://cloud.githubusercontent.com/assets/1012741/25342173/8d53ae64-28e1-11e7-8f26-e951ff03a080.png)

**Comment by jonjamcam** [comment]
@Hitrate You can try reducing CPU usage changing the value of the "Refresh Rate" in your .json file:

-![](https://github.com/elieserdejesus/JamTaba/wiki/images/Jamtaba_Manual/refresh_json.jpg)

The default value is 30 (these are GUI refresh cycles in Hz). Try reducing to 15 or less and you'll notice less CPU will be used. The drawback in this case is that the level meters will have a "slow" response, but it's a good trade off for better performance.
***
@elieserdejesus What happened to the meters in Logic?

![image](https://cloud.githubusercontent.com/assets/15310433/25345869/747a65d0-28ec-11e7-98e0-d2bf0ddd5053.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , the meters was messed, but is fixed now. After a clean compilation the meters are working fine.
