### ISSUE TITLE
gain button's method for choosing -12, 0 and +12

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#836]
The problem as I see it is that when you want to change gain to 0 and go from -12 to +12 with one click with no option to avoid this step you have a 24 dB increase in signal that can hurt your ears if not your speakers or phones.

I'm thinking on ways to avoid this. I have two ideas:

IDEA 1:

 use **left** mouse click for **-12** selection, **right** mouse click for **+12** selection and use **double click** for 0 selection (**reset**)

IDEA 2:

mouse **click and drag down** for **-12** selection, mouse **click and drag up** for **+12** selection and use **double click** for 0 selection (**reset**).

I think any of these two methods will retain the independence of selection and avoid the problem mentioned above.

EDIT:

IDEA 3: just adding **double click** for 0 selection (**reset**) to the current behavior could be easier to do I think and can solve the 24 dB gap too.

**Comment by elieserdejesus** [comment]
@jonjamcam , I will schedule this issue to next release.

**Comment by elieserdejesus** [comment]
@jonjamcam , I think this issue can be solved in next release, it's not high priority for v2.0.20.

**Comment by jonjamcam** [comment]
> I will schedule this issue to next release.

sure @elieserdejesus .

**Comment by Hitrate** [comment]
Sorry but I feel it's idiotic to consider various weird ways of manipulating the extreme fixed jump of 12db regardless. Make it several jumps that revert back to 0db instead of jumping up to +db's..Preferably in for instance 4db increments. Or a simple two button solution: +4db increments, -4db increments.

**Comment by elieserdejesus** [comment]
I'm working in a 2 buttons solution:
![image](https://user-images.githubusercontent.com/1012741/31417825-77f0f6a6-ae08-11e7-8148-7b096872c4ba.png)

> I feel it's idiotic to consider various weird ways

@Hitrate, please use more adequate words when mentioning the ideas posted here. This is NOT a forum. This is part of an open source software development enviroment. We need contributors and ideas. If everybody discuss the ideas using "acid language" the result will be "no contributors", including myself. Please not discourage the ideas. If you disagree just post another idea **without disqualify the original idea**. 

You used the word "idiotic". Can you imagine how many times I felt a big idiot spending my time programming JamTaba, after reading destructive comments in ninbot or here in github? Please, help me feel less idiotic. Please avoid poisoned and unecessary negative comments. This is very important for me, because if I feel very idiot the logic conclusion is very obvious, right? Why spend my time in this software? To read non sense comments from people paying absolutely nothing to play with something I'm working from years? How this situation can be acceptable from a logic point of view? No sense for me!

I'm spending many hours of my life in this software and I expect a polished language in the comments, I suppose this is the minimum.  

Please help to keep the **positive vibe**.  In an environment when people have **no obligations** the negativism will result in nothing, no software, no bug fixes, no issues implemented, etc.

Are you expecting negative comments will make me work harder? For free? While reading Bilo's nice comments in ninbot?  😄

**Comment by Hitrate** [comment]
Having to mention my suggestions on this topic twice because it seems from Jon’s suggestions, that he was going with an idea that didn’t take my already suggested points about this topic into consideration, so it came out that way to make my point the second time around!

Little did I know you where already working on a two button (I assume more incremental and less ear destructing implementation). I don’t see any reason for you to feel hurt, since the comment wasn’t at all directed at you! I Same story with the simple vs. user options in preferences debate we had months ago, where I had suggestions for some extra options for users in the preferences like quality settings. It seemed like you misunderstood again my points, which where to have more “expert” options in preferences. That suggestions was taken in the completely wrong way by you, so I laid off from commenting too much to avoid more needless negativity. But I get your point. I don’t wanna become another “Bilos” that’s for sure ;) my bad guys

**Comment by elieserdejesus** [comment]
> But I get your point. I don’t wanna become another “Bilos” that’s for sure ;) my bad guys

Thankksssssss @Hitrate , really thank you for understand the situation! I love you 😄 

> so it came out that way to make my point the second time around!

@Hitrate , **in this issue** you not posted before, so the discussion here is considering just the context of this issue. If we discussed something related with boost button in another issues I can't remember, honestly. I have 3 dogs, a job, wife and daughter, etc. And I work in another programming projects, no way to remember all discussions details. These github **issues** are my **memory** 😄 . If it's not in the issue discussion it's not in my memory too.
