### ISSUE TITLE
Common Room ambiance

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#856]
I've been thinking for a while about how to implement a common room ambiance for all players, but of course this will be available for Jamtaba users only :disappointed: 

How I imagine it working:

First let's say Jamtaba comes with a number of predefined ambiances like **hall, plate, studio, dry, church**, etc. (I don't know @elieserdejesus if this is a pain to code, but I think you had the idea of native effects for Jamtaba at some point).

When one user turns on let's say "hall", then all other users could be notified (using jamtaba server) of this and ask via chat button to vote. If you vote yes and there are enough votes, then the same ambiance is turned on for you too. Of course you could set another ambiance and ask for others to vote if you want or turn it off, but the idea is that all have a common room that sounds similar with one dry/wet level for fine tuning if we want (all this using common tools that we already use).

 The button inside the server that activates/deactivates the room ambiance could be like this:

![image](https://cloud.githubusercontent.com/assets/15310433/25560123/1cf714d2-2d21-11e7-8bde-dd93e8e88af5.png)

with a drop down menu for ambiance selection and level knob or fader (this last "fader" point is debatable because in real life when you enter a room you can't decide how much room you want :smile: ):

When you enter a room and there's already some ambiance set, just as the "last chord used" appear, a chat message could ask you if you wish to activate the button automatically.

 The disadvantage of this is that recordings will sound different over ninbot and ninjamer and non-jamtaba users will listen to a "different jam", but if the the room ambiance is subtle it can work pretty good in most cases.

**Comment by elieserdejesus** [comment]
@jonjamcam , the idea is interesting. I see 2 problems, and one you already mentioned:

1 - the another clients and server stream will not contain the ambience

2 - I'm not shure if the end result will be worth it because sometimes users enter in a **very dry jam** and just keep using a **lot of stereo delays and big hall reverbs**. In another jams people are **playing very dry sounds** in a more **"spacial" jam when many people are using big reverbs**. Sumarizing, in many jams the ambiences are not matching. I understand you are proposing a solution for these "bad ambience matching jams", but I'm not shure if this will be a solution or a new problem. In general, I think many ninjamers are not paying enough attention to ambience effects and these people will continue using big reverbs and/or dry sounds. In the end, we will add an overall ambience in an already "ambienced" sounds, because people will not turn off your big delays and reverbs. I'm afraid the end result will sound bad in already ambienced jams, and JamTaba will be guilty for the bad sound :)  

In dry jams the idea is very interesting, I see no problems.  

What you think about? What is your expectation about **overall ambience** mixed with **ninjamers ambience**?

**Comment by jonjamcam** [comment]
> I'm not shure if this will be a solution or a new problem.

True. It's important that new features simplify the experience.

> What you think about? What is your expectation about overall ambience mixed with ninjamers ambience?

For my part it depends a lot of who you're playing with. The Ninjam system allows beginners to play with experienced musicians "as equals" and this is very unusual in real life as I experienced in the past. So a tool like Ambiance is more for people who enjoy the natural sounding of their instrument (experienced musicians) I think. If you're in the stage of learning an instument, you probably try will to mask the lack of technique with lots of effects.

So with regards to average Ninjam users I'll say: most electric guitar players use little or no reverb, but a lot of distortion and their sound is likely to be mono. I this cases the ambiance could make the jam warmer and less harsh.

On the contrary, drummers (me included!) use a lot of reverb so here the result I agree with you could be very bad when mixing both effects.

 Maybe at this point in time it's too early for these kind of enhancements. As I see it, Jamtaba is pushing the Ninjam experience to a higher level with regards to Jam quality (audio and playing), so my conclusion is that over time (some years in the future) new players will reach a playing level that will make them enjoy their instruments with less effects because they play better.

 Of course by this time new beginners will appear too and everything will be the same lol (except we get older) . I guess the point here is that when Jamtaba becomes the most widely used client (and I think this will definitely be the case in the future) we'll have the critical mass for these kind of implementations to be useful.

Today, as you say, it will bring more problems than solutions.

**Comment by elieserdejesus** [comment]
@jonjamcam , I think we can keep the issue and the idea open, maybe we can see from another perspective in future. 

For example, I was discarded completely the Looper idea for a couple of years because make no sense for me (we already have VST loopers, etc). Things changed and now we have a cool embedded looper in JamTaba. Sometimes the we just need mature the ideas and get a better perspective.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
