### ISSUE TITLE
Ninjamroom Accessibility problem

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#88]
There is a problem with the design for accessibility here in relation with the BPI,BPM,Accent and shape
selections boxes.
While the mouseWheel is working good to change the values , there is a Yes/NO dialog that popup silently . If you were blind , you would be stuck here .

I can add a description to tell to the user that there is a box that will popup at the center of the screen ,
but that is not convenient . Why do we need that Yes/NO dialog finally ?

**Comment by elieserdejesus** [comment]
Ezee, I understand the problem of the popup. The screen reader don't catch the popup dialot text and buttons?

I'm askint this because we have other dialogs.

Your question about the BPM/BPI confirmation dialog is a good question, and now I thinking about "why I put this dialog" and I remember. The BPI and BPM combos are editable. So you can type a value and press RETURN to send a vote BPI/BPM change command. Sometimes the combos autocomplete feature propose bad values for BPI or BPM, so I added this dialog to confirm the value. Somethink like "You really want change the BPM to 237"? 

Now is clear this is a very bad solution. In the last commits I disable the autocomplete feature in BPI/BPM combo boxes, so we don't need this popup for confirmation.

Can you work in this fix?
If yes look in
```
NinjamRoomWindow::ninjamBpiComboChanged()
NinjamRoomWindow::ninjamBpmComboChanged
```

**Comment by Ezeer** [comment]
Done .
see https://github.com/elieserdejesus/JamTaba/commit/448cb05fd0802f3e5666525ac783755305a3eddf
