### ISSUE TITLE
JamTaba is closing when hit ESC by accident

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#883]
solution: show a prompt before exit to avoid close by accident.

**Comment by Hitrate** [comment]
I’ll just chime in here because I can.. I was a bit baffled by jon’s statement yesterday about not wanting to have user options in preferences but rather to keep it simple (I’m paraphrasing and generalizing) and now you’re suggesting something that’s obtrusive as a feature... I know we can all have different opinions, but I personally never understood the wish for some types of people to shoot down something (feature, extra function; extra settings , user chooses in preferences etc.) like, okay I get it maybe YOU don’t want to have these options because of x y and z. Maybe you don’t even want other people to have those options because of x y z. But maybe OTHER people might think these options are invaluable,
This whatever selfish reason YOU might have had, could then negatively affect the potential for other users of the software! 

Then I check my email today and read this suggestion which doesn’t add something positive to my life (I’ve always hated prompts and pop ups and stuff like that, and if I wanna close something by hitting ESC, it’s on purpose) - but where I to suggest this be a feature to turn on/off (or at least have a check mark to not bother me with the popup again after the first time seeing it) I’d probably get an argument like jon came with yesterday about not wanting to confuse the user and keep it simple and yadayadayada - you see what I mean ? It’s this incongruent egoistic thing that kinda ticks me off, because it’s not coming from a place of let’s make the best app ever, it’s more like a negative vibed “nooo that’s too confusing for people or no that would be too much for people to “understand”. Kinda like the quality discussion. I’m still baffled that the majority conclusion is to keep jamtaba at a low crappy mp3 quality instead of letting the somewhat few ninjammers we are, at least enjoy good quality streams from each other, rather than it be a geeky coding option that few know about. 

I just wanted to make this rant because it feels like some of the discussions about what to implement and the decisions that come from it, are not always ideal for all. Taking away potential features doesn’t help the geek, it only takes away the option in order to “keep it simple” of all things....and everyone else is left with the option of nothing.

Best Regards

Torben Scharling

**Comment by Hitrate** [comment]
Another note on prompts and “keeping it simple” vs obtrusive irritations: make the prompt when syncing to DAW auto go away -when the user has tried the click to sync button a few times, they know that they have to press play on their saw - no need to manually click away the annoying box every time.

Suggestion: auto-go-away for all prompts, or discussion about when why and where to prompt, and where not to...or a check box on the prompt giving you the option to pot out of these prompts in the future.

Best regards

Torben Scharling

**Comment by Hitrate** [comment]
*DAW not saw :)

**Comment by elieserdejesus** [comment]
@Hitrate 
> It’s this incongruent egoistic thing that kinda ticks me off, because it’s not coming from a place of let’s make the best app ever, it’s more like a negative vibed “nooo that’s too confusing for people or no that would be too much for people to “understand”. 

I'm shure many users think the **best app ever** is the **more simple and intuitive ever**. 


> Kinda like the quality discussion. I’m still baffled that the majority conclusion is to keep jamtaba at a low crappy mp3 quality instead of letting the somewhat few ninjammers we are, at least enjoy good quality streams from each other, rather than it be a geeky coding option that few know about.

Are you considering the impact of stream quality in servers traffic (more traffic = more money to keep the servers running)? And in ninjamers upload/download bandwith? I suppose you are living in a good country with very good internet services. Unfortunally (personal experience) this is not the case in many countries.

 If we just adopt high quality streams (without consider the side effects) a lot of people can be disconnected from servers (because server is exausted or the user bandwith is exausted), and JamTaba will be blamed.

**Comment by Hitrate** [comment]
But what is the consensus here? Make a dirt simple app that’s “easy to use” ? Make “Pro” options available and not a hidden feature because people in Nigeria need to be able to jam with an ISDN? I was comfortably ninjamming tethered to an iPhone 3GS back in 2009 or there abouts!

But it seems like you’re kinda missing my point a bit: you’re introducing new prompts - is that making things easier for the user? I know I’m being a bit negative here, but I just feel like some of these decisions are based on you guys’ own individual ideas about what the user wants, without perhaps fully understanding what the users actually want. 

I’m a user for instance. Do I wanna have to click left and right in jamtaba all the time wile jamming? No. I want it to manage levels and syncing automatically. Do I want prompts left and right that I have to click?  No I want my hands free to play on my instrument. Do I wish there where a lot of features that where not disregarded due to some beginner users wanting “simplicity” of cause! Do I want rooms with room for less people, so the jams don’t get flooded with “noise” ? Of cause. Do I want high quality streams ? You bet! Do I want “Pro” features like password protected rooms for certain players to gather and not be bothered by “uninvited” “newbies” ? I’ve wanted that for years. (Yes, without having to buy, setup, and run my own servers). Right now Mutantlab is the only channel with max 4 players. As far as I remember his room is better quality too, but don’t quote me on that. Only thing that sucks is his room is not auto recorded. I don’t see the problem in having high quality options/rooms. It could even be mead Quality settings button(s) on the mixer (or in preferences). It could be a per vote thing in the room, so Nigerian players can choose 32kbit if they wish, and other players can choose higher quality depending on their own needs...specific rooms could be capped to specific quality max and minimum etc. Ninbot has Ninbot Gold, doesn’t hurt to have options for users to donate to cover server costs. If anything, I think it’s about keeping an open mind to ideas and potentials, and not disregarding the niceness of having options. Instead of arguing “well there are players in Nigeria that don’t have steady wifi, and they are gonna then blame Jamtaba for it, thus we must keep the quality low” is like saying the lowest common denominator wins, always. That’s not the attitude I’d wanna have about it. But then again it’s not my project, I’m just brainstorming ideas and giving you my input :) Jamkazam has a neat way to test your system and tell you how many players your connection can handle - thís is the kind of thinking that’s right. Not just capping the system because some have poor connections.

Best Regards

Torben Scharling

**Comment by elieserdejesus** [comment]
> But what is the consensus here? Make a dirt simple app that’s “easy to use” ?

In my mind (open to changes) the consensus is **make a simple (but not dirt) app that’s easy to use**. Why the "dirt" word? You really see JTBA as a dirt app? If yes I'm interested (honestly). 

***
> you’re introducing new prompts - is that making things easier for the user? 

I think can be easier if user is hiting ESC by accident. I agree the prompts are shitty, but you proposed a simple solution before: **a checkable prompt**. Everybody will be happy with a checkable prompt 😄 . 

***
> I’m a user for instance. Do I wanna have to click left and right in jamtaba all the time wile jamming? No. I want it to manage levels and syncing automatically. Do I want prompts left and right that I have to click?  No I want my hands free to play on my instrument. Do I wish there where a lot of features that where not disregarded due to some beginner users wanting “simplicity” of cause! Do I want rooms with room for less people, so the jams don’t get flooded with “noise” ? Of cause. Do I want high quality streams ? You bet! Do I want “Pro” features like password protected rooms for certain players to gather and not be bothered by “uninvited” “newbies” ? I’ve wanted that for years. (Yes, without having to buy, setup, and run my own servers). Right now Mutantlab is the only channel with max 4 players. As far as I remember his room is better quality too, but don’t quote me on that.

Are all very good wishes, and I have many of the same wishes. **All these ideas are very very very very time consuming to implement**. In general terms **easy to use** means **very complex to implement**.

***

> I think it’s about keeping an open mind to ideas and potentials, and not disregarding the niceness of having options. Instead of arguing “well there are players in Nigeria that don’t have steady wifi, and they are gonna then blame Jamtaba for it, thus we must keep the quality low”

This Nigeria argument is your stuff 😄 , you are exaggerating to prove your point.

***

> It could even be mead Quality settings button(s) on the mixer (or in preferences). It could be a per vote thing in the room, so Nigerian players can choose 32kbit if they wish, and other players can choose higher quality depending on their own needs...specific rooms could be capped to specific quality max and minimum etc. 

Again these are very good ideas, but these ideas need be programmed in the server side. We can't change the servers quality from clients (JamTaba, ReaNinjam, wahjam, etc.). Off course is possible implement new servers (the easy task), and convince servers admins to use the new version (the hard part 😄 )

***

> But then again it’s not my project, I’m just brainstorming ideas and giving you my input :) 

I disagree, it's your project too (a little bit). Every contributor has a little piece of the cake. I'm the project manteiner, not the owner. Your ideas are very welcome.

***

> Jamkazam has a neat way to test your system and tell you how many players your connection can handle - thís is the kind of thinking that’s right. Not just capping the system because some have poor connections.

I agree, but this is complicated to program. 

*Quick mention about the JamKazam tests and internet quality in different countries*: JamKazam tell me I can't play online, because the number of players I can connect is ZERO 😄. ps: I was using 5 Mb down/1Mb up, in theory, because in Brazil the internet providers can (by law) deliver 70% of the bandwith.

**Comment by jonjamcam** [comment]
I think esc could be a nice and quick way to exit a server. And to exit jamtaba, maybe CTR-Q?

**Comment by elieserdejesus** [comment]
maybe a conditional behavior for esc key ?

If JTBA **is connected** in server ESC will just disconnect from server (not quit JTBA). 

If **not connected** in a server ESC will quit JamTaba.

**Comment by jonjamcam** [comment]
Yeah! That sounds good to me @elieserdejesus.
