### ISSUE TITLE
metronome and master levels not centered when connected to a server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#927]
![image](https://user-images.githubusercontent.com/15310433/31580320-4ed952be-b122-11e7-90ac-e6e38708d87a.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , this was intentional. What you think? In my eyes:
1 - the controls in bottom are more clean, we have (the illusion) more empty spaces
2 - the controls in bottom are cleary **secondary**, and the ninjam panel in center is clearly **primary**.

I'm ok with the centered version too. If you prefer the centered version is necessary change 2 lines: 
https://github.com/elieserdejesus/JamTaba/blob/2cc1539c9e43d583e9bd28840174e49fce948411/src/Common/gui/MainWindow.cpp#L1183
https://github.com/elieserdejesus/JamTaba/blob/2cc1539c9e43d583e9bd28840174e49fce948411/src/Common/gui/MainWindow.cpp#L1184

**Comment by jonjamcam** [comment]
I'm ok with it @elieserdejesus . Let's see what other's think about it :smile:
